/* 提出書類の保管台帳。AI未接続時はファイル名で分類し、不明は未分類にする。 */
(function(){
 const types=[['mitsumori','見積'],['youryou','施工要領書'],['daicho','写真台帳'],['hikaku','比較表'],['zumen','図面'],['houkoku','報告書'],['other','他資料']];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let dbPromise;
 function db(){return dbPromise||(dbPromise=new Promise((resolve,reject)=>{const q=indexedDB.open('nn_submission_files_v1',1);q.onupgradeneeded=()=>q.result.createObjectStore('files',{keyPath:'id'});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);}));}
 async function transaction(mode,action){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('files',mode),q=action(tx.objectStore('files'));tx.oncomplete=()=>resolve(q?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('保存中断'));});}
 function classify(name){const n=name.normalize('NFKC'),rules=[['mitsumori',/見積|estimate|quotation/i],['youryou',/施工要領|施工手順|method.statement/i],['daicho',/写真台帳|工事写真帳|photo.album/i],['hikaku',/比較表|比較検討|comparison/i],['zumen',/図面|平面図|立面図|断面図|納まり図|\.(dwg|jww|dxf)$/i],['houkoku',/報告書|調査報告|report/i]];const matches=rules.filter(([,r])=>r.test(n));if(matches.length===1)return matches[0][0];if(!matches.length&&/カタログ|工程表|議事録|契約書|取扱説明|catalog/i.test(n))return 'other';return '';}
 function property(pid){return props.find(p=>p.id===pid);}
 function refresh(p){document.querySelectorAll('#list .pcard[data-pid="'+p.id+'"] .pdocs').forEach(el=>el.innerHTML=window.nnSubmissionTable(p));if(typeof selectedId!=='undefined'&&selectedId===p.id&&typeof renderDetail==='function')renderDetail();}
 window.nnSubmissionTable=p=>'<table class="doc-matrix" data-nn-static aria-label="提出書類"><caption>提出書類</caption><thead><tr>'+types.map(([key,label])=>'<th scope="col"><button type="button" onclick="event.stopPropagation();nnSubmissionOpen('+p.id+',\''+key+'\')"><span'+(key==='youryou'?' data-s="要領書"':'')+'>'+label+'</span><img src="./icons/doc_'+key+'_s.png?v=2026-09-24c" width="56" height="56" decoding="async" alt=""></button></th>').join('')+'</tr></thead><tbody><tr>'+types.map(([key,label])=>{const count=(p.files||[]).filter(f=>f.saved&&f.docKind===key).length;return '<td><button type="button" class="doc-status '+(count?'stored':'')+'" title="'+label+'：'+(count?'保管済 '+count+'件':'未保管')+'" aria-label="'+label+'：'+(count?'保管済 '+count+'件':'未保管')+'" onclick="event.stopPropagation();nnSubmissionOpen('+p.id+',\''+key+'\')">'+(count?'○':'－')+'</button></td>';}).join('')+'</tr></tbody></table>';
 window.nnSubmissionOpen=function(pid,key){const p=property(pid);if(!p)return;selectedId=pid;curTab=key==='zumen'?'作成図面':'保管資料';showView('list');openDetailFull();};
 window.nnSubmissionControls=f=>f.submissionId?'<label class="doc-kind">書類種類 <select aria-label="書類種類" onchange="nnSubmissionKind(\''+esc(f.submissionId)+'\',this.value)"><option value="">未分類（種類を選択）</option>'+types.map(([k,n])=>'<option value="'+k+'"'+(f.docKind===k?' selected':'')+'>'+n+'</option>').join('')+'</select></label><button type="button" onclick="nnSubmissionDelete(\''+esc(f.submissionId)+'\')">削除</button>':'';
 window.nnSubmissionKind=async function(id,kind){if(kind&&!types.some(([k])=>k===kind))return;const p=props.find(p=>p.files.some(f=>f.submissionId===id));if(!p)return;try{const rec=await transaction('readonly',s=>s.get(id));if(!rec)return;rec.docKind=kind;rec.classifiedBy='manual';if(kind)rec.cat=kind==='zumen'?'zumen':'doc';await transaction('readwrite',s=>s.put(rec));Object.assign(p.files.find(f=>f.submissionId===id),{docKind:kind,cat:rec.cat});refresh(p);}catch(e){toast('変更を保存できませんでした。');}};
 window.nnSubmissionDelete=async function(id){const p=props.find(p=>p.files.some(f=>f.submissionId===id));if(!p||!confirm('この端末に保管した書類を削除しますか？'))return;try{await transaction('readwrite',s=>s.delete(id));const f=p.files.find(f=>f.submissionId===id);URL.revokeObjectURL(f.url);p.files=p.files.filter(f=>f.submissionId!==id);refresh(p);}catch(e){toast('削除できませんでした。');}};
 window.nnStoreSubmissionFiles=async function(pid,fileList){const p=property(pid);if(!p)return;await ready;let count=0,unknown=0;for(const file of Array.from(fileList)){try{const kind=classify(file.name),cat=kind?(kind==='zumen'?'zumen':'doc'):catOf(file.name),rec={id:crypto.randomUUID(),code:p.code,name:file.name,size:file.size,cat,docKind:kind,classifier:'filename',date:new Date().toLocaleDateString('ja-JP'),blob:file};await transaction('readwrite',s=>s.put(rec));p.files.push({name:rec.name,size:rec.size,cat,url:URL.createObjectURL(file),date:rec.date,submissionId:rec.id,docKind:kind,saved:true});count++;if(!kind&&cat!=='photo')unknown++;}catch(e){refresh(p);toast('書類を端末に保存できませんでした。空き容量などを確認してください。');return;}}refresh(p);toast(count+'件をこの端末に保存しました。'+(unknown?'未分類 '+unknown+'件は書類種類を選んでください。':'ファイル名から書類種類を判別しました。'));};
 let ready=Promise.resolve();document.addEventListener('DOMContentLoaded',()=>{ready=(async()=>{try{const records=await transaction('readonly',s=>s.getAll());for(const r of records){if(!r||!(r.blob instanceof Blob)||typeof r.code!=='string')continue;const p=props.find(p=>p.code===r.code);if(!p)continue;p.files.push({name:r.name,size:r.size,cat:r.cat,url:URL.createObjectURL(r.blob),date:r.date,submissionId:r.id,docKind:r.docKind,saved:true});}for(const p of props)if(p.files.length)refresh(p);}catch(e){/* 保存操作時にエラーを案内する。未保管を○にはしない。 */}})();});
})();
