/* 現場一覧の文字表。行列の移動は共通の表操作へ接続する。 */
(function(){
 const KEY='nn_record_view_v1';let pref={};try{const v=JSON.parse(localStorage.getItem(KEY)||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))pref=v;}catch(e){}
 const money=v=>v==null?'—':yen(v),date=v=>v instanceof Date&&!isNaN(v)?v.toLocaleDateString('ja-JP'):'—';
 const fields=[['code','番号',p=>p.code],['name','現場名',p=>p.name],['status','状態',p=>p.status],['moto','元請',p=>p.moto],['addr','住所',p=>p.addr],['tantou','担当者',p=>p.tantou],['kouhou','工法・仕様',p=>p.kouhou||p.hou],['maker','メーカー',p=>p.maker],['quantity','数量',p=>(p.m||0).toLocaleString()+(p.un||'㎡')],['order','請負金額',p=>money(p.order)],['profit','利益予定額',p=>money(profitOf(p))],['date','契約日・予定',p=>p.date],['genba','着工日・予定',p=>p.genba],['finish','完成日・予定',p=>p.stRaw==='kan'?p.kansei:(p.yotei||p.kansei)],['prog','進行度',p=>(p.prog||0)+'%'],['payment','入金予定日',p=>date(p.nbD)],['sh','支払条件',p=>p.sh],['tan','単価',p=>money(p.tan)+'/'+(p.un||'㎡')],['mat','材料代',p=>money(p.mat)],['jin','工賃',p=>money(p.jin)],['other','その他経費',p=>money((p.other||0)+(p.keihi||0))],['kbn','契約区分',p=>p.kbn||'材工'],['kizon','既存防水',p=>p.kizon||'不明'],['kind','工事区分',p=>p.kind||'改修'],['kouzou','構造',p=>p.kouzou||'RC'],['defect','不具合',p=>{const e=document.createElement('div');e.innerHTML=window.nnDefRow?nnDefRow(p,0):'';return e.textContent.trim();}],['extra','追加工事未回収',p=>exOpenCount(p)+'件'],['files','保管書類',p=>(p.files||[]).map(f=>f.name).join('、')],['tb','メモ',p=>p.tb]];
 pref.hidden=Array.isArray(pref.hidden)?pref.hidden.filter(k=>fields.some(f=>f[0]===k)&&k!=='name'):[];
 const style=document.createElement('style');style.textContent=`
 #nnRecordModes{display:inline-flex;gap:3px;flex:none;}#nnRecordModes button{font:inherit;font-size:13px;font-weight:800;border:1px solid #758476;padding:5px 10px;background:#fff8e7;color:#294d36;cursor:pointer;}#nnRecordModes button[aria-pressed=true]{background:#287d44;color:#fff;}
 #list .record-tools{display:flex;flex-wrap:wrap;gap:8px;align-items:center;padding:6px;background:#fff8e7;font-size:12px;}#list .record-tools button{font:inherit;cursor:pointer;}
 #recordFields{padding:8px;background:#fff8e7;display:flex;flex-wrap:wrap;gap:8px 16px;}#recordFields[hidden]{display:none;}#recordFields label{font-size:13px;white-space:nowrap;}
 #recordScroll{overflow:auto;max-width:100%;max-height:calc(100% - 42px);background:white;}#recordTable{border-collapse:separate;border-spacing:0;table-layout:auto;font-size:13px;width:max-content;min-width:100%;color:#242820;}#recordTable th,#recordTable td{padding:7px 10px;border-right:1px solid #c6ccbc;border-bottom:1px solid #c6ccbc;white-space:nowrap;text-align:left;}#recordTable th{position:sticky!important;top:0;z-index:5;background:#f4dfb5;cursor:grab;touch-action:none;}#recordTable td{cursor:grab;touch-action:pan-x;}#recordTable tr:nth-child(even){background:#f7f7ee;}#recordTable tr:hover{background:#fff0ca;}#recordTable button{font:inherit;font-weight:800;color:#176735;background:transparent;border:0;text-align:left;cursor:pointer;text-decoration:underline;}#recordTable .record-name{max-width:340px;white-space:normal;min-width:210px;}#recordTable td[data-field=tb]{min-width:200px;max-width:400px;white-space:normal;}
 html body #dashboard .nyuflex{align-items:stretch!important;}
 html body #dashboard .nyuflex>[data-widget-key="nyukin-calendar"]:not(.nn-widget-sized){display:flex;flex-direction:column;}
 html body #dashboard [data-widget-key="nyukin-calendar"]>.nn-widget-content{flex:1;min-height:300px;overflow:hidden!important;display:flex;flex-direction:column;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .ncal{display:flex!important;flex-direction:column;flex:1;min-height:0;width:100%;height:100%!important;}
 html body #dashboard [data-widget-key="nyukin-calendar"] #calbox{display:flex!important;flex-direction:column;flex:1;min-height:0;width:100%;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .calbox{width:100%;box-sizing:border-box;min-height:0;display:flex!important;flex-direction:column;flex:1;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .cal{width:100%!important;min-width:0!important;table-layout:fixed;flex:1;height:100%!important;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .cal th,html body #dashboard [data-widget-key="nyukin-calendar"] .cal td{width:auto!important;min-width:0!important;padding:2px;white-space:normal;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .calh{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:2px;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .callg{flex:0 0 auto;gap:4px 10px;margin-top:4px;}
 html body #dashboard [data-widget-key="nyukin-calendar"].nn-widget-sized>.nn-widget-content{min-height:0;}
 `;document.head.appendChild(style);
 function save(){try{localStorage.setItem(KEY,JSON.stringify(pref));}catch(e){toast('表示を変更しました。端末には保存できません。');}}
 const bar=document.createElement('span');bar.id='nnRecordModes';bar.innerHTML='<button type="button" data-mode="cards">カード</button><button type="button" data-mode="table">表一覧</button>';document.getElementById('toolbar').prepend(bar);
 function pressed(){bar.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String((pref.mode==='table'?'table':'cards')===b.dataset.mode)));}pressed();
 bar.onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;pref.mode=b.dataset.mode;save();pressed();render();};
 window.nnRenderRecordTable=function(arr,head){if(pref.mode!=='table')return false;const visible=fields.filter(f=>!pref.hidden.includes(f[0]));document.getElementById('list').innerHTML=head+'<div class="record-tools"><button type="button" id="recordFieldsToggle" aria-expanded="false">表示項目</button><button type="button" id="recordOrderReset">並び・幅を戻す</button><span>見出しをドラッグ：項目・列の移動 ／ 本文を上下にドラッグ：現場の行移動 ／ 現場名：詳細</span></div><div id="recordFields" hidden>'+fields.map(f=>'<label><input type="checkbox" value="'+f[0]+'" '+(!pref.hidden.includes(f[0])?'checked ':'')+(f[0]==='name'?'disabled':'')+'>'+nnE(f[1])+'</label>').join('')+'</div><div id="recordScroll"><table id="recordTable"><thead><tr>'+visible.map(f=>'<th data-field="'+f[0]+'">'+nnE(f[1])+'</th>').join('')+'</tr></thead><tbody>'+arr.map(p=>'<tr onclick="void(0)" data-record-id="'+nnE(p.code)+'">'+visible.map(f=>'<td data-row-id="'+nnE(p.code)+'" data-field="'+f[0]+'">'+(f[0]==='name'?'<button type="button" class="record-name" onclick="nnGoDetail('+Number(p.id)+')">'+nnE(p.name)+'</button>':nnE(f[2](p)||'—'))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'+(arr.length?'':'<p>該当する現場はありません。</p>')+'</div>';
 // 行の識別は値や現在の表示列に依存させない。
 document.querySelectorAll('#recordTable tbody tr').forEach(r=>r.setAttribute('onclick','void('+JSON.stringify(r.dataset.recordId)+')'));
 document.getElementById('recordFieldsToggle').onclick=()=>{const box=document.getElementById('recordFields');box.hidden=!box.hidden;document.getElementById('recordFieldsToggle').setAttribute('aria-expanded',String(!box.hidden));};
 document.getElementById('recordFields').onchange=e=>{pref.hidden=[...document.querySelectorAll('#recordFields input:not(:checked)')].map(x=>x.value);save();render();document.getElementById('recordFieldsToggle').click();};
 document.getElementById('recordOrderReset').onclick=()=>{for(const key of ['nn_table_layout_v1','nn_table_widths_v1']){try{const v=JSON.parse(localStorage.getItem(key)||'{}');for(const k of Object.keys(v))if(k===location.pathname+'|recordTable')delete v[k];localStorage.setItem(key,JSON.stringify(v));}catch(e){}}location.reload();};return true;};
})();
