/* 現場一覧の文字表。行列の移動は共通の表操作へ接続する。 */
(function(){
 const KEY='nn_record_view_v1';let pref={};try{const v=JSON.parse(localStorage.getItem(KEY)||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))pref=v;}catch(e){}
 let sortKey='',sortDir=-1;
 const money=v=>v==null?'—':yen(v),date=v=>v instanceof Date&&!isNaN(v)?v.toLocaleDateString('ja-JP'):'—';
 const fields=[['code','番号',p=>p.code],['name','現場名',p=>p.name],['status','状態',p=>p.status],['moto','元請',p=>p.moto],['addr','住所',p=>p.addr],['tantou','担当者',p=>p.tantou],['kouhou','工法・仕様',p=>p.kouhou||p.hou],['maker','メーカー',p=>p.maker],['quantity','数量',p=>(p.m||0).toLocaleString()+(p.un||'㎡')],['order','請負金額',p=>money(p.order)],['profit','利益予定額',p=>money(profitOf(p))],['date','契約日・予定',p=>p.date],['genba','着工日・予定',p=>p.genba],['finish','完成日・予定',p=>p.stRaw==='kan'?p.kansei:(p.yotei||p.kansei)],['prog','進行度',p=>(p.prog||0)+'%'],['payment','入金予定日',p=>date(p.nbD)],['sh','支払条件',p=>p.sh],['tan','単価',p=>money(p.tan)+'/'+(p.un||'㎡')],['mat','材料代',p=>money(p.mat)],['jin','工賃',p=>money(p.jin)],['other','その他経費',p=>money((p.other||0)+(p.keihi||0))],['kbn','契約区分',p=>p.kbn||'材工'],['kizon','既存防水',p=>p.kizon||'不明'],['kind','工事区分',p=>p.kind||'改修'],['kouzou','構造',p=>p.kouzou||'RC'],['defect','不具合',p=>{const e=document.createElement('div');e.innerHTML=window.nnDefRow?nnDefRow(p,0):'';return e.textContent.trim();}],['extra','追加工事未回収',p=>exOpenCount(p)+'件'],['files','保管書類',p=>(p.files||[]).map(f=>f.name).join('、')],['tb','メモ',p=>p.tb]];
 pref.hidden=Array.isArray(pref.hidden)?pref.hidden.filter(k=>fields.some(f=>f[0]===k)&&k!=='name'):[];
 const style=document.createElement('style');style.textContent=`
 #nnRecordModes{display:inline-flex;align-items:stretch;gap:7px;flex:none;padding:0 3px 4px 0;}
 #nnRecordModes button{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:50px;font:inherit;font-size:13px;font-weight:800;white-space:nowrap;border:2px solid #245735;border-radius:3px;padding:5px 10px;background:#fff8e7;color:#294d36;box-shadow:0 4px 0 #245735;cursor:pointer;transition:transform .08s,box-shadow .08s;}
 #nnRecordModes button img{display:block;width:48px;height:36px;object-fit:contain;}
 #nnRecordModes button:hover{background:#f3e5c3;}
 #nnRecordModes button:focus-visible{outline:3px solid #d5971d;outline-offset:3px;}
 #nnRecordModes button:active,#nnRecordModes button[aria-pressed=true]{transform:translateY(3px);box-shadow:0 1px 0 #184127;}
 #nnRecordModes button[aria-pressed=true]{background:#287d44;color:#fff;border-color:#184127;}
 html[data-nnphone="1"] #nnRecordModes{gap:5px;}
 html[data-nnphone="1"] #nnRecordModes button{padding:4px 7px;gap:5px;min-height:46px;font-size:12px;}
 html[data-nnphone="1"] #nnRecordModes button img{width:42px;height:32px;}
 #list .record-tools{display:flex;flex-wrap:wrap;gap:8px;align-items:center;padding:6px;background:#fff8e7;font-size:12px;}#list .record-tools button{font:inherit;cursor:pointer;}
 #recordFields{padding:8px;background:#fff8e7;display:flex;flex-wrap:wrap;gap:8px 16px;}#recordFields[hidden]{display:none;}#recordFields label{font-size:13px;white-space:nowrap;}
 #recordScroll{overflow:auto;max-width:100%;max-height:calc(100% - 42px);background:white;}#recordTable{border-collapse:separate;border-spacing:0;table-layout:auto;font-size:13px;width:max-content;min-width:100%;color:#242820;}#recordTable th,#recordTable td{padding:7px 10px;border-right:1px solid #c6ccbc;border-bottom:1px solid #c6ccbc;white-space:nowrap;text-align:left;}#recordTable th{position:sticky!important;top:0;z-index:5;background:#f4dfb5;cursor:grab;touch-action:none;user-select:none;}#recordTable td{cursor:grab;touch-action:pan-x;}#recordTable td:first-child{touch-action:none;}#recordTable .record-sort{padding:0 6px;margin-left:5px;text-decoration:none;font-size:11px;touch-action:manipulation;}#recordTable tr:nth-child(even){background:#f7f7ee;}#recordTable tr:hover{background:#fff0ca;}#recordTable button{font:inherit;font-weight:800;color:#176735;background:transparent;border:0;text-align:left;cursor:pointer;text-decoration:underline;}#recordTable .record-name{max-width:340px;white-space:normal;min-width:210px;}#recordTable td[data-field=tb]{min-width:200px;max-width:400px;white-space:normal;}
 html body #dashboard .nyuflex{align-items:stretch!important;}
 html body #dashboard .nyuflex>[data-widget-key="nyukin-calendar"]:not(.nn-widget-sized){display:flex;flex-direction:column;}
 html body #dashboard [data-widget-key="nyukin-calendar"]>.nn-widget-content{flex:1;min-height:300px;overflow:hidden!important;display:flex;flex-direction:column;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .ncal{display:flex!important;flex-direction:column;flex:1;min-height:0;width:100%;height:100%!important;}
 html body #dashboard [data-widget-key="nyukin-calendar"] #calbox{display:flex!important;flex-direction:column;flex:1;min-height:0;width:100%;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .calbox{width:100%;box-sizing:border-box;min-height:0;display:flex!important;flex-direction:column;flex:1;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .cal{width:100%!important;min-width:0!important;table-layout:fixed;flex:1;height:100%!important;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .cal th,html body #dashboard [data-widget-key="nyukin-calendar"] .cal td{width:auto!important;min-width:0!important;padding:2px;white-space:normal;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .calh{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:2px;}
 html body #dashboard [data-widget-key="nyukin-calendar"] .callg{flex:0 0 auto;gap:4px 10px;margin-top:4px;}
 html body #dashboard [data-widget-key="nyukin-calendar"].nn-widget-sized>.nn-widget-content{min-height:0;}
 `;document.head.appendChild(style);
 function save(){try{localStorage.setItem(KEY,JSON.stringify(pref));}catch(e){toast('表示を変更しました。端末には保存できません。');}}
 const bar=document.createElement('span');bar.id='nnRecordModes';bar.innerHTML='<button type="button" data-mode="cards" title="カード表示"><img src="./icons/view_cards.png?v='+NN_VER+'" alt="">カード</button><button type="button" data-mode="table" title="表一覧表示"><img src="./icons/view_table.png?v='+NN_VER+'" alt="">表一覧</button><button type="button" id="recordExcel" title="表示中の現場と項目をExcel形式でダウンロード">Excel出力</button>';document.getElementById('toolbar').prepend(bar);
 function pressed(){bar.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String((pref.mode==='table'?'table':'cards')===b.dataset.mode)));}pressed();
 bar.onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;pref.mode=b.dataset.mode;save();pressed();render();};
 function value(p,k){switch(k){case 'quantity':return p.m;case 'profit':return profitOf(p);case 'other':return (p.other||0)+(p.keihi||0);case 'extra':return exOpenCount(p);case 'payment':return p.nbD instanceof Date?p.nbD:null;case 'date':case 'genba':case 'finish':{const f=fields.find(f=>f[0]===k),v=f[2](p),m=String(v||'').match(/^(\d{4})[/-](\d{1,2})[/-](\d{1,2})$/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):v;}case 'order':case 'tan':case 'mat':case 'jin':case 'prog':return p[k];default:return fields.find(f=>f[0]===k)[2](p);}}
 function sorted(arr){if(!sortKey)return arr;return [...arr].sort((a,b)=>{let x=value(a,sortKey),y=value(b,sortKey);if(x==null||x==='')return y==null||y===''?0:1;if(y==null||y==='')return -1;if(x instanceof Date)x=x.getTime();if(y instanceof Date)y=y.getTime();return sortDir*(typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'ja',{numeric:true}));});}
 document.getElementById('recordExcel').onclick=()=>{try{const table=pref.mode==='table'?document.getElementById('recordTable'):null,cols=table?[...table.querySelectorAll('thead th')].map(th=>fields.find(f=>f[0]===th.dataset.field)):fields.filter(f=>!pref.hidden.includes(f[0])),byCode=new Map(filtered().map(p=>[p.code,p])),rows=table?[...table.tBodies[0].rows].map(r=>byCode.get(r.dataset.recordId)).filter(Boolean):sorted(filtered());const data=rows.map(p=>cols.map(f=>{let v=value(p,f[0]),format='';if(['order','profit','tan','mat','jin','other'].includes(f[0]))format='#,##0';if(f[0]==='quantity')format='#,##0.##"'+(p.un||'㎡').replaceAll('"','')+'"';if(f[0]==='prog'){v=Number(v||0)/100;format='0%';}return {value:v,format};}));nnDownloadRecordExcel(cols.map(f=>f[1]),data);toast('Excelをダウンロードしました（'+rows.length+'件）');}catch(e){toast('Excel出力に失敗しました。もう一度お試しください。');console.error(e);}};
 window.nnRenderRecordTable=function(arr,head){if(pref.mode!=='table')return false;arr=sorted(arr);const visible=fields.filter(f=>!pref.hidden.includes(f[0]));document.getElementById('list').innerHTML=head+'<div class="record-tools"><button type="button" id="recordFieldsToggle" aria-expanded="false">表示項目</button><button type="button" id="recordOrderReset">並び・幅を戻す</button><span>見出しをドラッグ：項目・列の移動 ／ 本文を上下にドラッグ：現場の行移動 ／ 現場名：詳細</span></div><div id="recordFields" hidden>'+fields.map(f=>'<label><input type="checkbox" value="'+f[0]+'" '+(!pref.hidden.includes(f[0])?'checked ':'')+(f[0]==='name'?'disabled':'')+'>'+nnE(f[1])+'</label>').join('')+'</div><div id="recordScroll"><table id="recordTable"><thead><tr>'+visible.map(f=>'<th data-field="'+f[0]+'">'+nnE(f[1])+'<button type="button" class="record-sort" data-sort="'+f[0]+'" aria-label="'+nnE(f[1])+'の並べ替え" title="クリックで降順・昇順を切り替え">'+(sortKey===f[0]&&sortDir===1?'▲':'▼')+'</button></th>').join('')+'</tr></thead><tbody>'+arr.map(p=>'<tr onclick="void(0)" data-record-id="'+nnE(p.code)+'">'+visible.map(f=>'<td data-row-id="'+nnE(p.code)+'" data-field="'+f[0]+'">'+(f[0]==='name'?'<button type="button" class="record-name" onclick="nnGoDetail('+Number(p.id)+')">'+nnE(p.name)+'</button>':nnE(f[2](p)||'—'))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'+(arr.length?'':'<p>該当する現場はありません。</p>')+'</div>';
 document.querySelectorAll('#recordTable .record-sort').forEach(b=>b.onclick=()=>{sortDir=sortKey===b.dataset.sort?-sortDir:-1;sortKey=b.dataset.sort;window.nnClearTableRowOrder?.(document.getElementById('recordTable'));render();});
 // 行の識別は値や現在の表示列に依存させない。
 document.querySelectorAll('#recordTable tbody tr').forEach(r=>r.setAttribute('onclick','void('+JSON.stringify(r.dataset.recordId)+')'));
 document.getElementById('recordFieldsToggle').onclick=()=>{const box=document.getElementById('recordFields');box.hidden=!box.hidden;document.getElementById('recordFieldsToggle').setAttribute('aria-expanded',String(!box.hidden));};
 document.getElementById('recordFields').onchange=e=>{pref.hidden=[...document.querySelectorAll('#recordFields input:not(:checked)')].map(x=>x.value);save();render();document.getElementById('recordFieldsToggle').click();};
 document.getElementById('recordOrderReset').onclick=()=>{for(const key of ['nn_table_layout_v1','nn_table_widths_v1']){try{const v=JSON.parse(localStorage.getItem(key)||'{}');for(const k of Object.keys(v))if(k===location.pathname+'|recordTable')delete v[k];localStorage.setItem(key,JSON.stringify(v));}catch(e){}}location.reload();};return true;};
})();
