const fs=require('fs'),path=require('path');const {chromium}=require('C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
// ポインターの整数pxによる最大3cmの誤差を認める。数値指定は1e-8で照合。
const source=process.argv[2]||'zumen_sekisan.html';const root=process.cwd();let bad=0;const ok=(n,c,v)=>{console.log((c?'○':'★NG')+' '+n+' '+JSON.stringify(v));if(!c)bad++;};
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
for(const phone of [false,true]){const p=await b.newPage({viewport:{width:phone?393:1600,height:phone?852:900},isMobile:phone,hasTouch:phone});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route('https://rect.test/**',async r=>{let f=decodeURIComponent(new URL(r.request().url()).pathname.slice(1));if(f==='zumen_sekisan.html')f=source;const file=path.join(root,f);if(fs.existsSync(file)&&fs.statSync(file).isFile())await r.fulfill({path:file});else await r.fulfill({status:404,body:''});});
await p.goto('https://rect.test/zumen_sekisan.html');await p.evaluate(()=>{try{nnZMenuClose();}catch{} state.polys=[];state.parts=[];state.scaleM=1;cellPx=34;ox=20;oy=190;setTool('box');draw();});
const tap=async(x,y)=>{const pt=await p.evaluate(([x,y])=>{const r=cv.getBoundingClientRect();return {x:r.left+(ox+x*cellPx)*r.width/(cv.width/devicePixelRatio),y:r.top+(oy+y*cellPx)*r.height/(cv.height/devicePixelRatio)}},[x,y]);if(phone)await p.evaluate(({x,y})=>{for(const t of ['pointerdown','pointermove','pointerup'])cv.dispatchEvent(new PointerEvent(t,{pointerId:71,pointerType:'touch',isPrimary:true,clientX:x-36,clientY:y+52,bubbles:true}));},pt);else await p.evaluate(({x,y})=>cv.dispatchEvent(new MouseEvent('mousedown',{button:0,clientX:x,clientY:y,bubbles:true})),pt);};
await tap(1,1);await tap(4.37,5.23);let pts=await p.evaluate(()=>state.polys[0]?.pts);ok((phone?'スマホ':'PC')+' 完成寸法3.37×4.23m',pts&&Math.abs(pts[1].x-pts[0].x-3.37)<0.03&&Math.abs(pts[2].y-pts[1].y-4.23)<0.03,pts);
await p.evaluate(()=>{boxP1=null;state.polys=[{pts:[{x:1.13,y:1.17},{x:5.37,y:1.17},{x:5.37,y:7.23},{x:1.13,y:7.23}],edges:Array.from({length:4},()=>({h:0,w:0,k:'free'}))}];draw();});
await tap(6.5,1.2);await tap(8.2,7.2);pts=await p.evaluate(()=>state.polys[1]?.pts);ok((phone?'スマホ':'PC')+' 離れた既存屋根と上下を一致',pts&&Math.abs(pts[0].y-1.17)<1e-8&&Math.abs(pts[2].y-7.23)<1e-8,pts);
await p.evaluate(()=>{state.polys=[];boxP1={x:5,y:6};mouse.gx=2;mouse.gy=3;draw();});
let hit=await p.evaluate(()=>nnLabHit.find(x=>x.kind==='boxdim'));ok('寸法札が数値指定できる',!!hit,hit);
if(hit){await p.evaluate(([h,phone])=>{const r=cv.getBoundingClientRect(),x=r.left+h.x*r.width/(cv.width/devicePixelRatio),y=r.top+h.y*r.height/(cv.height/devicePixelRatio);if(phone){cv.dispatchEvent(new PointerEvent('pointerdown',{pointerId:73,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,bubbles:true}));cv.dispatchEvent(new PointerEvent('pointerup',{pointerId:73,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,bubbles:true}));}else cv.dispatchEvent(new MouseEvent('mousedown',{button:0,clientX:x,clientY:y,bubbles:true}));},[hit,phone]);await p.evaluate(()=>{const d=document.querySelector('#nnNumDlg.open');if(d){d.querySelector('input').value='1.735';d.querySelector('.okb').click();}else{const press=k=>document.querySelector('#nnPad2 [data-k="'+k+'"]').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));press('cl');for(const k of '1.735')press(k);press('ok');}});await p.evaluate(()=>{const d=document.querySelector('#nnNumDlg.open');if(d){d.querySelector('input').value='11.025';d.querySelector('.okb').click();}else{const press=k=>document.querySelector('#nnPad2 [data-k="'+k+'"]').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));press('cl');for(const k of '11.025')press(k);press('ok');}});pts=await p.evaluate(()=>state.polys[0]?.pts);ok('数値指定の完成寸法と左上方向',pts&&Math.abs(pts[0].x-3.265)<1e-8&&Math.abs(pts[0].y+5.025)<1e-8&&pts[2].x===5&&pts[2].y===6,pts);}
ok('実行エラーなし',errs.length===0,errs);await p.close();}
await b.close();process.exitCode=bad?1:0;})();
