const fs=require('fs'),path=require('path'),{chromium}=require((process.platform==='win32'?'C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright':'/opt/node22/lib/node_modules/playwright'));
let bad=0;const ok=(c,m,v)=>{console.log((c?'○ ':'★NG ')+m+' '+JSON.stringify(v));if(!c)bad++;};
(async()=>{const b=await chromium.launch({executablePath:(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'),args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:1500,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/zumen_sekisan.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='sheet.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});await p.goto('https://sheet.test/zumen_sekisan.html');await p.evaluate(()=>{nnZMenuClose();state.scaleM=1;state.polys=[{pts:[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4}],edges:Array.from({length:4},()=>({k:'para',h:600,w:400})),holes:[],lv:0}];state.parts=[];state.d3sheet=[];state.active=0;setTab('d3');});await p.waitForFunction(()=>T&&T.group&&T.group.children.length>3);
const results=await p.evaluate(()=>{const V=q=>new THREE.Vector3(...q);return [.41,.45,.50].map(x=>{const f=nnSheetSizeFaces({point:V([x,.55,.406]),n:V([0,0,1])},300,300,0);const ranges={};f.forEach(g=>{(ranges[g.id.ei]||= {})[g.id.k]=[Math.min(...g.pts.map(q=>q[0])),Math.max(...g.pts.map(q=>q[0]))];});return {x,ranges};});});
results.forEach(r=>{const a=r.ranges[0],b=r.ranges[3];ok(a&&b&&['cham','top'].every(k=>a[k]&&b[k]&&Math.abs(a.wall[1]-a[k][1])<1e-7&&Math.abs(b.wall[0]-b[k][0])<1e-7),'入隅の両側で外縁が壁・面取り・天端まで一直線',r);});
await p.evaluate(()=>{state.polys=[{pts:[{x:0,y:0},{x:4,y:0},{x:4,y:2},{x:2,y:2},{x:2,y:4},{x:0,y:4}],edges:Array.from({length:6},()=>({k:'para',h:600,w:400})),holes:[],lv:0}];dirty3d=true;build3D();});
const snap=await p.evaluate(()=>{const a=new THREE.Vector3(2,.2,1.594),b=new THREE.Vector3(1.594,.23,2),n=new THREE.Vector3(-1,0,0);const w=nnSheetOrthoSnap(b,a,n,[a]);return w&&w.toArray();});ok(snap&&Math.abs(snap[1]-.2)<1e-8,'出隅の反対側へ同じ高さで直角に打点',snap);
await p.evaluate(()=>{d3ViewIso();T.theta=Math.PI*1.25;T.phi=1.15;T.tx=1.65;T.tz=1.65;T.r=3.8;T.rev++;nnSheetStart({n:'増貼り',col:'#cc0000'},'draw');nnCond.close();});await p.waitForFunction(()=>{const k=T.camera.position.toArray().join();window.__stable=window.__last===k?(window.__stable||0)+1:0;window.__last=k;return __stable>4;});
const screen=async(w)=>p.evaluate(w=>{let v=new THREE.Vector3(...w).project(T.camera),r=T.renderer.domElement.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};},w);
let a=await screen([2,.2,1.594]);await p.mouse.click(a.x,a.y);let c=await screen([1.594,.23,2]);await p.mouse.move(c.x,c.y);await p.evaluate(()=>nnD3Dims());const dims=await p.locator('#nnD3Dims').textContent();ok((dims.match(/mm/g)||[]).length>=2&&dims.includes('水平から 0°'),'1点目から出隅まで・出隅から照準まで寸法と傾き表示',dims);
await p.mouse.click(c.x,c.y);
for(const w of [[1.594,.012,2],[1.25,.012,2],[1.25,.012,1.25],[2,.012,1.25],[2,.012,1.594]]){const q=await screen(w);await p.mouse.click(q.x,q.y);}
await p.mouse.click(a.x,a.y);
const finished=await p.evaluate(()=>state.d3sheet.map(s=>s.faces.map(f=>({k:f.id.k,w:f.pts.map(q=>new THREE.Vector3(...f.p).addScaledVector(new THREE.Vector3(...f.u),q[0]).addScaledVector(new THREE.Vector3(...f.v),q[1]).toArray())}))));
ok(finished.length===1&&finished[0].filter(f=>f.k==='wall').length===2,'出隅の両壁と平場まで閉じて完成',finished);
const square=f=>f.w.every((p,i)=>{let a=f.w[(i+f.w.length-1)%f.w.length].map((x,j)=>x-p[j]),b=f.w[(i+1)%f.w.length].map((x,j)=>x-p[j]);let dot=a.reduce((s,x,j)=>s+x*b[j],0),cross=Math.hypot(a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]);return Math.abs(dot)<1e-6||cross<1e-6;});
ok(finished.length===1&&finished[0].every(square),'完成形の全辺が平行・直角（途中の一直線点は許容）');
await p.screenshot({path:'.codex-finalizer/corner-draw-preview.png'});ok(errors.length===0,'実行エラーなし',errors);
}finally{await b.close();}process.exitCode=bad?1:0;})().catch(e=>{console.error(e);process.exitCode=1;});

