const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/node22/lib/node_modules/playwright');let bad=0;const ok=(v,n,d)=>{console.log((v?'○ ':'★NG ')+n+' '+JSON.stringify(d??''));if(!v)bad++;};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});for(const mobile of [false,true]){const c=await b.newContext({viewport:mobile?{width:393,height:852}:{width:1754,height:950},isMobile:mobile,hasTouch:mobile,serviceWorkers:'block',reducedMotion:'reduce',...(mobile?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'}:{})});await c.addInitScript(m=>localStorage.setItem('nn_view_mode',m?'mobile':'pc'),mobile);await c.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/kirokucho_demo.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='dash.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://dash.test/kirokucho_demo.html');await p.waitForFunction(()=>document.querySelectorAll('#dashboard .httl').length===10);await p.evaluate(()=>document.fonts.ready);
const v=await p.evaluate(()=>{const h=document.querySelector('.httl'),a=[...document.querySelectorAll('.dpanel')].find(p=>p.querySelector('img[src*="hpic_taio"]')),sc=a.querySelector('.scrollbox'),pos=document.querySelector('.yoy.positive');return {frame:getComputedStyle(h,'::before').borderImageSource,font:getComputedStyle(h).fontSize,bar:parseFloat(getComputedStyle(document.querySelector('.cbar')).borderTopWidth),alerts:a.querySelectorAll('.alert-row').length,allAlerts:sc.scrollHeight<=sc.clientHeight+1,positive:pos&&getComputedStyle(pos).color,header:getComputedStyle(document.querySelector('.mini-tbl th')).backgroundColor,grip:getComputedStyle(document.querySelector('.nn-col-grip'),'::after').content,panels:document.querySelectorAll('[data-panel-id]').length,kpi:document.querySelector('.kgrps').getBoundingClientRect().height};});
ok(v.frame.includes('.svg')&&parseFloat(v.font)> (mobile?14:18),'滑らかなSVG枠と約1.1倍見出し',v.font);ok(v.bar<=1.5&&v.bar>=.8,'予実バーの外枠を細く',v.bar);ok(v.alerts===6&&v.allAlerts,'要対応6件をスクロールなしで表示',v);ok(v.positive==='rgb(20, 89, 165)','前年同期プラスを青');ok(v.header==='rgb(244, 223, 181)'&&v.grip==='none','表見出し別色・灰色棒なし');ok(v.panels===10,'全主要枠の移動と四辺調整');
if(v.panels===10){
 const graph=p.locator('[data-panel-id="monthly"] .seg').filter({visible:true}).first();await graph.scrollIntoViewIfNeeded();const r=await graph.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);const tip=await p.locator('#tip').boundingBox();ok(tip&&Math.min(Math.abs(tip.x-r.x),Math.abs(tip.x+tip.width-r.x))<360&&Math.min(Math.abs(tip.y-r.y),Math.abs(tip.y+tip.height-r.y))<90,'月別吹き出しが対象の棒の近く',{r,tip});await p.mouse.move(0,0);
 const panel=p.locator('[data-panel-id="yojitsu"]'),edge=panel.locator('[data-edge="s"]');await edge.scrollIntoViewIfNeeded();let r0=await panel.boundingBox(),g=await edge.boundingBox();await p.mouse.move(g.x+g.width/2,g.y+g.height/2);await p.mouse.down();await p.mouse.move(g.x+g.width/2,g.y+g.height/2+45,{steps:5});await p.mouse.up();let r1=await panel.boundingBox();ok(Math.abs(r1.height-r0.height-45)<4,'下辺ドラッグで枠の高さ調整',{before:r0.height,after:r1.height});
 const src=p.locator('[data-panel-id="juchu"] h4'),dest=p.locator('[data-panel-id="yojitsu"] h4');await src.scrollIntoViewIfNeeded();await dest.scrollIntoViewIfNeeded();let sr=await src.boundingBox(),dr=await dest.boundingBox();if(sr.y>0&&sr.y<750){await p.mouse.move(sr.x+60,sr.y+12);await p.mouse.down();await p.mouse.move(dr.x+80,dr.y+12,{steps:6});await p.mouse.up();await p.waitForFunction(()=>document.querySelector('.nn-panel-grid>.dpanel')?.dataset.panelId==='juchu');ok(await p.locator('.nn-panel-grid>.dpanel').first().getAttribute('data-panel-id')==='juchu','見出しドラッグで枠順序移動');}
 await p.reload();await p.waitForFunction(()=>document.querySelector('[data-panel-id="yojitsu"].nn-panel-fixed'));ok(true,'枠サイズの再読込復元');
 const table=p.locator('[data-panel-id="bugakari"] table');await table.scrollIntoViewIfNeeded();let headers=await table.locator('tr').first().locator('th').allTextContents();let cells=await table.locator('tr').nth(1).locator('td').allTextContents();let a=await table.locator('th').first().boundingBox(),z=await table.locator('th').last().boundingBox();await p.mouse.move(a.x+20,a.y+a.height/2);await p.mouse.down();await p.mouse.move(z.x+20,z.y+z.height/2,{steps:5});await p.mouse.up();ok((await table.locator('th').last().textContent()).trim()===headers[0].trim()&&(await table.locator('tr').nth(1).locator('td').last().textContent()).trim()===cells[0].trim(),'列移動で項目と全内容が連動');
 if(await table.locator('tr').count()>2){let first=await table.locator('tr').nth(1).textContent();a=await table.locator('tr').nth(1).locator('td').first().boundingBox();z=await table.locator('tr').nth(2).locator('td').first().boundingBox();await p.mouse.move(a.x+20,a.y+a.height/2);await p.mouse.down();await p.mouse.move(z.x+20,z.y+z.height/2,{steps:5});await p.mouse.up();ok((await table.locator('tr').nth(2).textContent())===first,'行移動で現場データの対応を保持');}
 const height=table.locator('.nn-table-height>div');await height.scrollIntoViewIfNeeded();let tb=await table.boundingBox(),hr=await height.boundingBox();await p.mouse.move(hr.x+hr.width/2,hr.y+hr.height/2);await p.mouse.down();await p.mouse.move(hr.x+hr.width/2,hr.y+hr.height/2+50,{steps:5});await p.mouse.up();let ta=await table.boundingBox();ok(Math.abs(ta.height-tb.height-50)<4,'表全体の高さドラッグ',{before:tb.height,after:ta.height});
 await p.reload();await p.waitForFunction(()=>document.querySelector('[data-panel-id="bugakari"] table'));ok((await p.locator('[data-panel-id="bugakari"] th').last().textContent()).trim()===headers[0].trim(),'列順序を再読込で復元');
 await p.evaluate(()=>document.getElementById('dashboard').scrollTop=0);await p.screenshot({path:'_check/dashusability-'+(mobile?'mobile':'pc')+'.png'});
}
ok(errors.length===0,'実行エラーなし',errors);if(mobile)ok(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),'スマホ横はみ出しなし');await c.close();}await b.close();process.exitCode=bad?1:0;})();
