const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE);let bad=0;const ok=(v,n,d)=>{console.log((v?'○ ':'★NG ')+n+' '+JSON.stringify(d??''));if(!v)bad++;};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH});for(const mobile of [false,true]){const c=await b.newContext({viewport:mobile?{width:393,height:852}:{width:1754,height:950},isMobile:mobile,hasTouch:mobile,serviceWorkers:'block',...(mobile?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'}:{})});await c.addInitScript(m=>{const mode=m?'mobile':'pc';localStorage.setItem('nn_view_mode',mode);localStorage.setItem('nn_dash_widgets_v1',JSON.stringify({[mode+'|nyukin-table']:{x:0,y:0,width:900,height:160}}));},mobile);await c.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(process.argv[2]){if(u.pathname==='/kirokucho_demo.html')f=path.resolve('_before-payment.html');if(u.pathname==='/dashboard_widgets.js')f=path.resolve('_before-payment-widgets.js');}return u.hostname==='dash.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://dash.test/kirokucho_demo.html');await p.waitForFunction(()=>document.querySelectorAll('[data-panel-id]').length===10&&document.querySelector('[data-widget-key="nyukin-table"]'));await p.evaluate(()=>document.fonts.ready);
const taio=p.locator('[data-panel-id="taio"]');ok(await taio.locator('.taio-tbl tbody tr').count()===6,'要対応6物件を表で表示');ok(await taio.locator('.nn-widget-move').count()===0,'物件間の移動つまみと余白を除去');
const payment=p.locator('[data-panel-id="nyukin"]'),w=payment.locator('[data-widget-key="nyukin-table"]');async function separated(){return payment.evaluate(e=>{const a=e.querySelector('[data-widget-key="nyukin-table"]').getBoundingClientRect(),b=(e.querySelector('[data-widget-key="nyukin-calendar"]')||e.querySelector('.ncal')).getBoundingClientRect();return a.right<=b.left+1||b.right<=a.left+1||a.bottom<=b.top+1||b.bottom<=a.top+1;});}ok(await separated(),'旧版で保存した崩れた配置を重ならず表示');
if(!process.argv[2]){async function drag(loc,dx,dy){await loc.scrollIntoViewIfNeeded();const r=await loc.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+r.width/2+dx,r.y+r.height/2+dy,{steps:8});await p.mouse.up();}
await drag(w.locator('[data-edge="e"]'),-80,0);ok(await separated(),'幅縮小後も重ならない');await drag(w.locator('[data-edge="se"]'),150,60);ok(await separated(),'縦横拡大後も重ならない');
const calendar=payment.locator('[data-widget-key="nyukin-calendar"]');await calendar.scrollIntoViewIfNeeded();const dest=await calendar.boundingBox();await w.locator('.nn-widget-move').scrollIntoViewIfNeeded();const start=await w.locator('.nn-widget-move').boundingBox();await p.mouse.move(start.x+35,start.y+start.height/2);await p.mouse.down();await p.mouse.move(start.x+80,start.y+80,{steps:6});await p.mouse.up();ok(await separated(),'並べ替え後も重ならない');
await w.locator('.nn-widget-move button').click();ok(await separated(),'配置を戻す操作');ok(await w.evaluate(e=>e.style.position==='relative'&&!e.style.height),'サイズと位置を復元');
const before=await payment.locator('#calbox').textContent();await payment.locator('.calnav').last().click();ok((await payment.locator('#calbox').textContent())!==before,'カレンダー月送りを維持');
await p.reload();await p.waitForFunction(()=>document.querySelector('[data-widget-key="nyukin-calendar"]'));ok(await separated(),'再読込後も重ならない');ok(await payment.locator('.nn-widget-move button').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return r.left>=p.left&&r.right<=p.right&&r.bottom<=p.bottom+1;})),'PC/スマホの配置を戻すボタンが枠内');await taio.screenshot({path:'_check/payment-taio-'+(mobile?'mobile':'pc')+'.png'});await payment.screenshot({path:'_check/payment-safe-'+(mobile?'mobile':'pc')+'.png'});}
ok(!errors.length,'実行エラーなし',errors);await c.close();}await b.close();process.exitCode=bad?1:0;})();
