const fs=require('fs'),path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/node22/lib/node_modules/playwright');let bad=0;const ok=(v,n,d)=>{console.log((v?'○ ':'★NG ')+n+' '+JSON.stringify(d??''));if(!v)bad++;};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});for(const mobile of [false,true]){
const c=await b.newContext({viewport:mobile?{width:393,height:852}:{width:1754,height:950},isMobile:mobile,hasTouch:mobile,serviceWorkers:'block',reducedMotion:'reduce',...(mobile?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'}:{})});await c.addInitScript(m=>localStorage.setItem('nn_view_mode',m?'mobile':'pc'),mobile);
await c.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/kirokucho_demo.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='dash.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});
const p=await c.newPage(),err=[];p.on('pageerror',e=>err.push(e.message));await p.goto('https://dash.test/kirokucho_demo.html');await p.waitForFunction(()=>document.querySelectorAll('#dashboard .httl').length===10);await p.evaluate(()=>document.fonts.ready);
const v=await p.evaluate(()=>{const panels=[...document.querySelectorAll('#dashboard .dpanel')],st=getComputedStyle(document.querySelector('.stbar')),k=getComputedStyle(document.querySelector('.kgrps'));return {buttons:document.querySelectorAll('.dash-settings-btn').length,kpi:k.borderColor===st.borderColor&&k.borderWidth===st.borderWidth&&k.backgroundColor==='rgb(255, 255, 255)',borders:panels.every(p=>getComputedStyle(p).borderColor===st.borderColor&&getComputedStyle(p).borderWidth===st.borderWidth),rows:panels.map(p=>{const a=p.querySelector('.httl').getBoundingClientRect(),b=p.querySelector('.dash-settings-btn')?.getBoundingClientRect();return b?Math.abs((a.top+a.bottom-b.top-b.bottom)/2):999;}),gap:getComputedStyle(document.querySelector('#dashboard')).gap,bar:getComputedStyle(document.querySelector('.cbar i')).backgroundImage,labels:[...document.querySelectorAll('.cline:not(.cdown)>.lb')].map(x=>getComputedStyle(x).fontSize),border:parseFloat(getComputedStyle(document.querySelector('.cbar')).borderTopWidth),profitBorder:parseFloat(getComputedStyle(document.querySelector('.cbar i:last-child')).borderLeftWidth)};});
ok(v.kpi&&v.borders,'KPI外枠と全主要枠が検索帯と一致',v);ok(v.buttons===10&&v.rows.every(x=>x<2),'10設定ボタンを見出しと同列',v.rows);ok(v.gap==='12px','主要枠の共通12px間隔');ok(v.bar.includes('linear-gradient')&&new Set(v.labels).size===1&&v.border>=.8&&v.border<=1.5&&v.profitBorder>1,'光沢・ラベル統一・粗利境界の太枠');
if(v.buttons===10){for(const mode of ['amount','both','percent']){await p.locator('.dash-settings-btn').first().click();await p.locator('#dashCostMode').selectOption(mode);await p.locator('#dashSettingSave').click();await p.waitForFunction(m=>document.querySelector('[data-cost-mode]')?.dataset.costMode===m,mode);const texts=await p.locator('.cbar i').allTextContents();ok(texts.every(t=>mode==='amount'?t.includes('万')&&!t.includes('%'):mode==='both'?t.includes('万')&&t.includes('%'):t.includes('%')&&!t.includes('万')),'予実の表示切替 '+mode,texts.slice(0,5));}
 await p.locator('.dash-settings-btn').first().click();await p.locator('#dashCostMode').selectOption('both');await p.locator('#dashSettingSave').click();await p.reload();await p.waitForFunction(()=>document.querySelector('[data-cost-mode="both"]'));ok(true,'金額と％の再読込復元');
 const expected=await p.evaluate(()=>{const a=props.filter(p=>p.stRaw==='kan'&&(!dashRange.from||p.fbD>=new Date(dashRange.from))&&(!dashRange.to||p.fbD<=new Date(dashRange.to)));return a.reduce((s,p)=>s+p.y[0],0);});const actual=await p.locator('.cbar').first().locator('[data-cost="0"]').getAttribute('data-amount');ok(Number(actual)===expected,'材料見積金額を物件から独立集計',{expected,actual});
 const table=p.locator('.sekou-tbl');await table.scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('.sekou-tbl .nn-col-grip'));let grip=table.locator('.nn-col-grip').first();await grip.scrollIntoViewIfNeeded();let before=await table.locator('tr').first().locator('th').first().boundingBox(),g=await grip.boundingBox();await p.mouse.move(g.x+g.width/2,g.y+g.height/2);await p.mouse.down();await p.mouse.move(g.x+g.width/2+55,g.y+g.height/2,{steps:5});await p.mouse.up();let after=await table.locator('tr').first().locator('th').first().boundingBox();ok(Math.abs(after.width-before.width-55)<4,'実ドラッグで列だけ55px拡大',{before:before.width,after:after.width});
 await p.reload();await p.waitForFunction(()=>document.querySelector('.sekou-tbl.nn-col-sized'),null,{timeout:5000});await p.locator('.sekou-tbl').scrollIntoViewIfNeeded();let restored=await p.locator('.sekou-tbl th').first().boundingBox();ok(Math.abs(restored.width-after.width)<3,'列幅の再読込復元',{after:after.width,restored:restored.width});
 ok(await p.evaluate(()=>[...document.querySelectorAll('table')].every(t=>!t.rows.length||t.querySelector('.nn-col-grip'))),'全表に列幅操作');
 await p.evaluate(()=>document.getElementById('dashboard').scrollTop=0);await p.screenshot({path:'_check/dashlayout-'+(mobile?'mobile':'pc')+'.png'});
}
ok(!err.length,'実行エラーなし',err);if(mobile)ok(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),'スマホ画面横はみ出しなし');await c.close();}await b.close();process.exitCode=bad?1:0;})();
