const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/node22/lib/node_modules/playwright');let bad=0;function ok(v,n,d){console.log((v?'○ ':'★NG ')+n+' '+JSON.stringify(d??''));if(!v)bad++;}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'}),c=await b.newContext({viewport:{width:1754,height:950},serviceWorkers:'block',reducedMotion:'reduce'});await c.route('**/*',r=>{const u=new URL(r.request().url()),f=path.resolve(decodeURIComponent(u.pathname).slice(1));return u.hostname==='dash.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://dash.test/kirokucho_demo.html');await p.waitForFunction(()=>document.querySelectorAll('[data-panel-id]').length===10);await p.evaluate(()=>document.fonts.ready);
async function drag(loc,dx,dy){await loc.scrollIntoViewIfNeeded();const r=await loc.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+r.width/2+dx,r.y+r.height/2+dy,{steps:8});await p.mouse.up();}
const panel=p.locator('[data-panel-id="yojitsu"]');let before=await panel.boundingBox();await drag(panel.locator('[data-edge="e"]'),-80,0);let after=await panel.boundingBox();ok(after.width<before.width-55&&after.width>before.width-105,'右辺で幅を縮小',{before:before.width,after:after.width});let w=after.width;await drag(panel.locator('[data-edge="w"]'),-50,0);after=await panel.boundingBox();ok(after.width>w+30,'左辺で幅を拡大');let h=after.height;await drag(panel.locator('[data-edge="n"]'),0,-40);after=await panel.boundingBox();ok(Math.abs(after.height-h-40)<4,'上辺で高さを拡大');await p.reload();await p.waitForFunction(()=>document.querySelector('[data-panel-id="yojitsu"].nn-panel-fixed'));let restored=await panel.boundingBox();ok(Math.abs(restored.width-after.width)<3&&Math.abs(restored.height-after.height)<3,'幅・高さの保存復元');
const table=p.locator('[data-panel-id="bugakari"] table');await table.scrollIntoViewIfNeeded();const th=table.locator('th').first();let title=(await th.textContent()).trim(),w0=(await th.boundingBox()).width;await drag(th.locator('.nn-col-grip'),45,0);let w1=(await th.boundingBox()).width;const a=await th.boundingBox(),z=await table.locator('th').last().boundingBox();await p.mouse.move(a.x+25,a.y+a.height/2);await p.mouse.down();await p.mouse.move(z.x+25,z.y+z.height/2,{steps:5});await p.mouse.up();await p.reload();await p.waitForFunction(()=>document.querySelector('[data-panel-id="bugakari"] table'));const last=p.locator('[data-panel-id="bugakari"] th').last();await last.scrollIntoViewIfNeeded();ok((await last.textContent()).trim()===title&&Math.abs((await last.boundingBox()).width-w1)<3,'幅変更した列を移動しても幅と項目の対応を保存',{original:w0,resized:w1,restored:(await last.boundingBox()).width});
const row=p.locator('[data-panel-id="bugakari"] tr').nth(1);h=(await row.boundingBox()).height;await drag(row.locator('.nn-row-grip'),0,30);ok(Math.abs((await row.boundingBox()).height-h-30)<3,'各行の高さ調整');
const arr=await p.locator('[data-panel-id="moto"] .nn-th-label').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),a=e.querySelector('.sortbtn')?.getBoundingClientRect();return a?Math.abs((r.top+r.bottom-a.top-a.bottom)/2):0;}));ok(arr.every(x=>x<2),'受注額を含む並べ替え矢印が文字のすぐ右');
await p.evaluate(()=>{props.filter(x=>x.stRaw==='mit').forEach(x=>x.order=1000);renderDash();});await p.waitForFunction(()=>document.querySelector('.yoy.negative'));ok(await p.locator('.yoy.negative').first().evaluate(e=>getComputedStyle(e).color)==='rgb(182, 34, 33)','前年同期マイナスを赤');
await p.evaluate(()=>showView('list'));ok(await p.locator('#dashboard').isHidden(),'配置機能追加後も一覧への切替を維持');ok(!errors.length,'実行エラーなし',errors);await b.close();process.exitCode=bad?1:0;})();
