/* §446 ダッシュボードの完成表示・透明余白・絞り込みをPC/スマホで確認。 */
const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/node22/lib/node_modules/playwright');
let bad=0;function ok(c,n,v){console.log((c?'○ ':'★NG ')+n+' '+JSON.stringify(v));if(!c)bad++;}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
for(const mode of ['pc','list','mobile']){
const c=await b.newContext({viewport:mode==='pc'?{width:1754,height:950}:{width:393,height:852},screen:mode==='pc'?{width:1754,height:950}:{width:393,height:852},isMobile:mode!=='pc',hasTouch:mode!=='pc',reducedMotion:'reduce',serviceWorkers:'block',...(mode==='pc'?{}:{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'})});
await c.addInitScript(m=>localStorage.setItem('nn_view_mode',m),mode);
await c.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/kirokucho_demo.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='dash.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});
const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://dash.test/kirokucho_demo.html');await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})));});
const v=await p.evaluate(()=>{const hs=[...document.querySelectorAll('#dashboard .httl')];const norm={hpic_yojitsu:[253,0,245],hpic_taio:[173,19,156],hpic_nyukin:[248,0,245]};return {note:!!document.querySelector('.kgnote'),sample:document.querySelector('header').innerText.includes('サンプルデータ'),border:getComputedStyle(document.querySelector('#dashboard .stbar')).borderTopWidth,heads:hs.filter(h=>h.querySelector('img')).map(h=>{const s=getComputedStyle(h),im=h.querySelector('img'),r=im.getBoundingClientRect(),hr=h.getBoundingClientRect(),z=hr.width/h.offsetWidth,k=im.src.match(/hpic_\w+/)[0],n=norm[k]||[im.naturalWidth,0,im.naturalWidth];return {text:h.innerText,top:parseFloat(s.paddingTop),bottom:parseFloat(s.paddingBottom),visibleWidth:r.width*(n[2]-n[1])/n[0]/z,gap:(hr.left+parseFloat(s.paddingLeft)*z-r.left-r.width*n[2]/n[0])/z};}),buttons:[...document.querySelectorAll('#dashboard .stchip')].map(e=>{const s=getComputedStyle(e);return [parseFloat(s.paddingTop),parseFloat(s.paddingBottom)];})};});
ok(!v.note&&!v.sample,mode+' 不要な説明2か所なし');ok(parseFloat(v.border)>=1.8,mode+' 検索帯の枠2px');ok(v.heads.every(x=>x.top===x.bottom&&x.top<=5),mode+' 見出しの上下余白を圧縮して同寸');ok(v.heads.every(x=>Math.abs(x.visibleWidth-(mode==='pc'?40:32))<.3&&Math.abs(x.gap-6)<.3),mode+' 全9アイコンの見える幅・文字との6px間隔',v.heads);ok(v.buttons.every(x=>x[0]===x[1]&&x[0]<=3),mode+' ボタン上下余白');
if(process.env.DASH_SCREENSHOT)await p.screenshot({path:path.join(process.env.DASH_SCREENSHOT,'dashboard-'+mode+'.png')});await p.locator('#dashboard .dfil .stchip').first().click();ok(await p.locator('#nnPortal.dfmenu.open').count()===1,mode+' 年度メニュー開閉');await p.locator('#nnPortal.dfmenu.open input').first().check();ok(await p.locator('#dashboard .filbar').count()===1,mode+' 絞り込み実操作');await p.evaluate(()=>dfResetAll());
ok(errors.length===0,mode+' 実行エラーなし',errors);await c.close();}
await b.close();process.exitCode=bad?1:0;})();


