/* 保存と保存済データを開くが上帯にあり、画像・機能・収まりが正しいことを確認する。 */
const fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const source=process.argv[2]||'zumen_sekisan.html',root=process.cwd();let bad=0;
const ok=(n,c,v)=>{console.log((c?'○':'★NG')+' '+n+' '+JSON.stringify(v));if(!c)bad++;};
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
for(const phone of [false,true]){const p=await b.newPage({viewport:{width:phone?393:1754,height:phone?852:982},isMobile:phone,hasTouch:phone});const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route('https://savehead.test/**',async r=>{let f=decodeURIComponent(new URL(r.request().url()).pathname.slice(1));if(f==='zumen_sekisan.html')f=source;const q=path.join(root,f);fs.existsSync(q)?r.fulfill({path:q}):r.fulfill({status:404,body:''});});
await p.goto('https://savehead.test/zumen_sekisan.html');await p.waitForTimeout(1300);
if(phone){await p.waitForSelector('#askHdBtn',{timeout:5000});const menu=await p.evaluate(()=>{const h=document.querySelector('header'),icon=h.querySelector('.hicon'),title=h.querySelector('h1'),help=document.getElementById('hdHelp'),ask=document.getElementById('askHdBtn');const r=x=>{const q=x.getBoundingClientRect();return {left:q.left,right:q.right,top:q.top,bottom:q.bottom,width:q.width,height:q.height,display:getComputedStyle(x).display}};return{menu:document.body.classList.contains('nn-zmenu'),header:r(h),back:r(h.querySelector('.nn-back')),icon:r(icon),title:r(title),help:r(help),ask:r(ask),titleText:title.querySelector('img')?.alt};});ok('スマホ入口のページ絵と図面・積算見出し',menu.menu&&menu.icon.display!=='none'&&menu.title.display!=='none'&&menu.icon.width>0&&menu.title.width>=107&&menu.titleText==='図面・積算',menu);ok('スマホ入口の上帯が393pxで一行・はみ出しなし',[menu.back,menu.icon,menu.title,menu.help,menu.ask].every(x=>x.top>=menu.header.top-1&&x.bottom<=menu.header.bottom+1)&&menu.ask.right<=393&&menu.header.right<=393,menu);}
await p.evaluate(()=>{try{nnZMenuClose();}catch{}});
const q=await p.evaluate(()=>{const h=document.querySelector('header').getBoundingClientRect(),s=document.getElementById('tl_save'),o=document.getElementById('tl_open'),a=s&&s.getBoundingClientRect(),c=o&&o.getBoundingClientRect();return{inHead:!!(s&&o&&s.closest('header')&&o.closest('header')),inToolbar:!!document.querySelector('#toolbar #tl_save,#toolbar #tl_open'),save:s&&s.textContent.trim(),open:o&&o.textContent.trim(),imgs:[s,o].map(x=>{const i=x&&x.querySelector('img');return i&&[i.naturalWidth,i.naturalHeight,i.getAttribute('src')]}),fit:!!(a&&c&&a.left<c.left&&a.top>=h.top-1&&c.right<=innerWidth+1&&c.bottom<=h.bottom+1),header:[h.left,h.right,h.top,h.bottom],buttons:a&&c?[[a.left,a.right,a.top,a.bottom],[c.left,c.right,c.top,c.bottom]]:null};});
ok((phone?'スマホ':'PC')+' 上帯へ移動し作図面から撤去',q.inHead&&!q.inToolbar,q);ok((phone?'スマホ':'PC')+' 新画像と名称',q.imgs.every(x=>x&&x[0]===1254&&x[1]===1254&&/2026-09-15f/.test(x[2]))&&q.save==='保存'&&q.open==='保存済データを開く',q);ok((phone?'スマホ':'PC')+' 上帯と画面内に収まる',q.fit,q);if(process.env.NN_SHOT&&!phone)await p.screenshot({path:process.env.NN_SHOT});
await p.evaluate(()=>document.getElementById('tl_save').click());let dlg=await p.evaluate(()=>!!document.getElementById('nnSaveBox'));ok((phone?'スマホ':'PC')+' 保存ボタンが動く',dlg,dlg);await p.evaluate(()=>document.getElementById('nnSaveBox')?.remove());await p.evaluate(()=>document.getElementById('tl_open').click());dlg=await p.evaluate(()=>!!document.getElementById('nnDwgList'));ok((phone?'スマホ':'PC')+' 保存済データを開くボタンが動く',dlg,dlg);ok((phone?'スマホ':'PC')+' 実行エラーなし',errs.length===0,errs);await p.close();}
await b.close();process.exitCode=bad?1:0;})().catch(e=>{console.error(e);process.exit(1)});
