const fs=require('fs'),path=require('path'),vm=require('vm');const{chromium}=require('C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..');let bad=0;function check(v,n){console.log((v?'○ ':'★NG ')+n);if(!v)bad++;}
(async()=>{
 const handlers={},cacheHits=new Map();let fetches=0,inflight=0,peak=0;const response=()=>({status:200,type:'basic',clone(){return this;}});const ctx={URL,Request,Response,Set,self:{location:{href:'https://test.test/sw.js',origin:'https://test.test'},addEventListener:(k,f)=>handlers[k]=f,skipWaiting:async()=>{},clients:{claim:async()=>{}}},caches:{open:async()=>({add:async()=>{inflight++;peak=Math.max(peak,inflight);await Promise.resolve();inflight--;},match:async req=>cacheHits.get(typeof req==='string'?req:req.url),put:async()=>{}}),keys:async()=>[],delete:async()=>{}},fetch:async()=>{fetches++;return response();}};vm.runInNewContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),ctx);let install;handlers.install({waitUntil:p=>install=p});await install;check(peak<=6,'更新時の同時読込みは6本以内');const req=new Request('https://test.test/common.css');cacheHits.set(req.url,response());for(let i=0;i<5;i++){let result;handlers.fetch({request:req,respondWith:p=>result=p,waitUntil:()=>{}});await result;}check(fetches===0,'保存済み共通素材の5回再利用で追加通信0');
 const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{for(const phone of [false,true]){const c=await b.newContext({viewport:phone?{width:390,height:844}:{width:1440,height:900},isMobile:phone,hasTouch:phone,serviceWorkers:'block'});await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='qa.test')return r.abort();if(u.pathname==='/table-fixture.html')return r.fulfill({contentType:'text/html',body:'<!doctype html><html><body><div>test</div><script src="table_resize.js"></script><script src="table_layout.js"></script></body></html>'});const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));return fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.fulfill({status:404,body:''});});const p=await c.newPage();const names=['index','kirokucho_demo','zumen_sekisan','genba_map_v36','hacchu','kokkosho','camera','library','shiyo_toroku','yougo','zairyo_toroku'];for(const n of names){await p.goto('http://qa.test/'+n+'.html');const state=await p.evaluate(()=>{const es=[...document.querySelectorAll('button.nn-compact')];return{n:es.length,ok:es.every(e=>{const s=getComputedStyle(e);return parseFloat(s.paddingTop)<=2.01&&parseFloat(s.paddingBottom)<=2.01;}),script:!!document.querySelector('script[src*="compact_buttons"]')};});check(state.script&&state.ok,n+' 文字ボタン上下2px '+(phone?'スマホ':'PC'));}
 await p.goto('http://qa.test/hacchu.html');await p.locator('.gchip').click();await p.locator('.gfilter-menu input').first().uncheck();check(await p.locator('.grow.st-kou').count()===0,'記録帳式ステータスメニューで絞り込み');await p.locator('.filter-reset').first().click();
 const order=await p.locator('.gchip').evaluate(e=>{const s=getComputedStyle(e);return ['backgroundImage','color','borderRadius','fontWeight','paddingTop','paddingBottom'].map(k=>s[k]);});await p.screenshot({path:path.join(root,'.research/order-exact-'+phone+'.png')});
 await p.goto('http://qa.test/kirokucho_demo.html');await p.evaluate(()=>showView('list'));const record=await p.locator('.stchip').first().evaluate(e=>{const s=getComputedStyle(e);return ['backgroundImage','color','borderRadius','fontWeight','paddingTop','paddingBottom'].map(k=>s[k]);});check(JSON.stringify(order)===JSON.stringify(record),'発注の絞り込みボタンは記録帳と同じ実測デザイン');
 await p.goto('http://qa.test/table-fixture.html');
 const scan=await p.evaluate(async()=>{const native=document.querySelectorAll.bind(document);let calls=0;document.querySelectorAll=s=>{if(s==='table:not([data-nn-static])')calls++;return native(s);};await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);calls=0;const d=document.createElement('div');document.body.append(d);for(let i=0;i<5;i++){d.textContent='更新'+i;await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);}const quiet=calls;const table=document.createElement('table');table.innerHTML='<tr><th>材料</th><th>数量</th></tr><tr><td>試験</td><td>2</td></tr>';d.append(table);await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);const grip=table.querySelector('.nn-col-grip');if(grip)grip.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));return{quiet,grips:table.querySelectorAll('.nn-col-grip').length,sized:table.classList.contains('nn-col-sized')};});console.log('table metrics',scan);check(scan.quiet===0&&scan.grips===2&&scan.sized,'無関係な5更新は全表走査0・新規表の幅変更は維持');
 await p.goto('http://qa.test/genba_map_v36.html');if(phone){await p.locator('#panelBtn').click();await p.waitForFunction(()=>document.querySelector('#panel').getBoundingClientRect().left>=0);}await p.waitForFunction(()=>document.querySelector('.kic img'));const icon=await p.locator('.kic img').first().evaluate(e=>{const r=e.getBoundingClientRect(),q=e.parentElement.getBoundingClientRect();return r.width>=q.width-3&&r.height>=q.height-3;});check(icon,'マップ工法画像は枠の内側いっぱい');check(await p.locator('.mch.ms').first().evaluate(e=>+getComputedStyle(e).fontWeight>=900),'仕様タグは太字900');await p.screenshot({path:path.join(root,'.research/map-icon-'+phone+'.png')});await c.close();}}finally{await b.close();}process.exitCode=bad?1:0;
})().catch(e=>{console.log('★NG',e);process.exitCode=1;});
