const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await b.newPage({viewport:{width:1600,height:900}});
p.on('console',m=>{ if(/DBG/.test(m.text())) console.log(m.text()); });
await p.goto('file:///home/user/osamarinavi_bousui/kirokucho_demo.html'); await p.waitForTimeout(2200);
await p.evaluate(()=>showView('list')); await p.waitForTimeout(1300);
await p.click('#list .pcard .pmemo'); await p.waitForTimeout(300);
console.log('textarea?', await p.evaluate(()=>!!document.querySelector('#list .pcard .pmemo textarea')));
await p.keyboard.type('テストメモ');
console.log('typed value:', await p.evaluate(()=>{const t=document.querySelector('#list .pcard .pmemo textarea'); return t?t.value:'(なし)';}));
await p.click('#toolbar'); await p.waitForTimeout(700);
console.log('tb:', await p.evaluate(()=>props.find(x=>x.id===+document.querySelector('#list .pcard').dataset.pid).tb));
await b.close();})();
