const fs=require('fs'),path=require('path');const{chromium}=require('C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');let bad=0;function check(v,n){console.log((v?'○ ':'★NG ')+n);if(!v)bad++;}
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{for(const phone of [false,true]){const c=await b.newContext({viewport:phone?{width:390,height:844}:{width:1440,height:900},isMobile:phone,hasTouch:phone,serviceWorkers:'block'});await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='ui.test')return r.abort();let p=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(process.env.UI_BEFORE&&/\/(hacchu|genba_map_v36)\.html$/.test(u.pathname))p=path.join(root,'.research',path.basename(p,'.html')+'-before.html');return fs.existsSync(p)&&fs.statSync(p).isFile()?r.fulfill({path:p}):r.fulfill({status:404,body:''});});const p=await c.newPage(),err=[];p.setDefaultTimeout(8000);p.on('pageerror',e=>err.push(e.message));
 await p.goto('http://ui.test/hacchu.html');await p.locator('.gq').fill('東京');await p.waitForFunction(()=>document.querySelector('.gq').value==='東京'&&document.querySelectorAll('.grow').length<42,{},{timeout:5000});check(await p.locator('.gq').evaluate(e=>e===document.activeElement),'検索後も入力位置を維持 '+phone);
 check(await p.locator('.gstart').count()>0,'記録帳型の情報カードと専用発注ボタン '+phone);if(process.env.UI_BEFORE){await p.goto('http://ui.test/genba_map_v36.html');check(await p.locator('#siteSearch').count()>0,'現場マップの一覧検索 '+phone);await c.close();continue;}
 await p.locator('.gq').pressSequentially('流通',{delay:180});check(await p.locator('.gq').inputValue()==='東京流通','検索語を途切れず追加入力');
 check(await p.locator('.grow').count()===1,'一致する現場だけ表示');await p.screenshot({path:path.join(root,'.research/order-new-'+phone+'.png')});
 await p.locator('.gstart').click();const quantities=p.locator('.qty');await quantities.first().fill('2');await quantities.first().press('Tab');const result=await p.evaluate(()=>({total:draftTotal(),expected:draft.lines[0].p*2,text:document.querySelector('.total-line .big').textContent,disabled:document.querySelector('.order-actions .btn-ok').disabled}));check(result.total===result.expected&&result.total>0&&!result.disabled,'数量入力で合計と確認ボタン更新');
 check(await quantities.first().inputValue()==='2','入力値維持');if(phone)check(await p.locator('.item-tbl').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'スマホ明細は横スクロール不要');await p.screenshot({path:path.join(root,'.research/order-edit-'+phone+'.png'),fullPage:true});await p.locator('.order-actions .btn-ok').click();check(await p.locator('.sheet').innerText().then(t=>t.includes('東京流通')&&t.includes('発注書')),'実操作で発注書の完成内容まで確認');
 await p.getByRole('button',{name:'← 明細に戻る'}).click();check(await quantities.first().inputValue()==='2','確認から戻って数量維持');await p.evaluate(()=>showView('hist'));check(await p.locator('.hrow').count()>0,'既存履歴表示');await p.locator('.hrow .btn-mini').last().click();check(await p.locator('.qty').count()>0,'前回の発注から明細再利用');
 await p.goto('http://ui.test/genba_map_v36.html');await p.waitForFunction(()=>typeof filteredSites==='function');if(phone)await p.locator('#panelBtn').click();
 await p.locator('#siteSearch').fill('八軒アパート');check(await p.locator('.site').count()===1,'マップで現場名を絞り込み');await p.locator('.site').click();check(await p.evaluate(()=>siteById(selId).name.includes('八軒アパート')),'現場選択が地図の選択状態へ接続');if(phone)await p.locator('#panelBtn').click();
 await p.locator('#siteSearch').fill('該当なしXYZ');check(await p.locator('.site-empty').isVisible(),'0件時の案内');await p.locator('.site-empty button').click();check(await p.locator('.site').count()===100,'条件クリアで全件復帰');await p.locator('[data-f=work]').click();check(await p.locator('.site').count()===14,'施工中14件の絞り込み');
 await p.screenshot({path:path.join(root,'.research/map-list-'+phone+'.png')});if(phone){await p.locator('#toggle').click();await p.waitForFunction(()=>document.getElementById('panel').getBoundingClientRect().right<=0);}
 // API未設定で地図が開かないことを確認。ここからは地図接続後のUI単体検査（描画APIは対象外）。
 check(await p.locator('#setup').isVisible(),'API未設定案内を維持');await p.locator('#setup').evaluate(e=>e.style.display='none');await p.locator('#toolFab').click();check(await p.locator('#drawBtn').isVisible()&&await p.locator('#oneClickBtn').isVisible(),'計測ツールを明示的に開ける');
 const bounds=await p.evaluate(()=>{const els=['searchBar','viewToggle','toolFab'].map(id=>document.getElementById(id).getBoundingClientRect());return els.every(r=>r.left>=-1&&r.right<=document.documentElement.clientWidth+1)&&els.every((r,i)=>els.every((q,j)=>i===j||r.right<=q.left+1||q.right<=r.left+1||r.bottom<=q.top+1||q.bottom<=r.top+1));});check(bounds,'地図検索・表示切替・ツールが重ならず画面内');await p.screenshot({path:path.join(root,'.research/map-tools-'+phone+'.png')});await p.locator('#toolFab').click();check(!await p.locator('#drawBtn').isVisible(),'計測ツールを閉じて地図を広く表示');
 check(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),'マップ横はみ出しなし '+phone);check(err.length===0,'実行エラーなし '+err.join(';'));await c.close();}}
 finally{await b.close();}process.exitCode=bad?1:0;})().catch(e=>{console.log('★NG',e);process.exitCode=1;});
