const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await b.newPage({viewport:{width:1600,height:900}});
p.on('pageerror',e=>console.log('[err]',e.message));
await p.goto('http://localhost:8899/kirokucho_demo.html'); await p.waitForTimeout(2200);
await p.evaluate(()=>showView('list')); await p.waitForTimeout(1300);
const el=await p.$('#list .pcard');
const box=await el.boundingBox();
console.log('card box', box);
await p.mouse.click(box.x+box.width*0.5, box.y+10); await p.waitForTimeout(300);
console.log('armed after 1st:', await p.evaluate(()=>document.querySelectorAll('#list .pcard.armed').length));
console.log('what is at that point:', await p.evaluate(([x,y])=>{const t=document.elementFromPoint(x,y); return t? t.className+'|'+t.tagName : 'none';},[box.x+box.width*0.5, box.y+10]));
await p.mouse.click(box.x+box.width*0.5, box.y+10); await p.waitForTimeout(800);
console.log('detail:', await p.evaluate(()=>!!document.querySelector('#detail .dhead h2')));
await b.close();})();
