const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let bad=0;const ok=(c,m,v)=>{console.log((c?'○ ':'★NG ')+m+(v===undefined?'':' '+JSON.stringify(v)));if(!c)bad++;};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/zumen_sekisan.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='sizecorner.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});await p.goto('https://sizecorner.test/zumen_sekisan.html');await p.evaluate(()=>{nnZMenuClose();state.scaleM=1;state.polys=[{pts:[{x:0,y:0},{x:4,y:0},{x:4,y:2},{x:2,y:2},{x:2,y:4},{x:0,y:4}],edges:Array.from({length:6},()=>({k:'para',h:600,w:250})),holes:[],lv:0}];state.parts=[];state.d3sheet=[];state.active=0;setTab('d3');});await p.waitForFunction(()=>T&&T.group&&T.group.children.length>3);

await p.evaluate(()=>{state.polys[0].edges.forEach(e=>e.h=300);state.genkyo='body';dirty3d=true;build3D();window.topAudit=function(faces){const polys=faces.filter(f=>f.id.k==='top').map(f=>f.pts.map(q=>{const w=new THREE.Vector3(...f.p).addScaledVector(new THREE.Vector3(...f.u),q[0]).addScaledVector(new THREE.Vector3(...f.v),q[1]);return [w.x,w.z];}));function inside(P,p){let yes=false;for(let i=0,j=P.length-1;i<P.length;j=i++){const a=P[i],b=P[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}const covered=q=>polys.some(P=>inside(P,q)),bad=[];polys.forEach(P=>P.forEach((a,i)=>{const b=P[(i+1)%P.length],dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy);if(Math.abs(dx)<1e-7||Math.abs(dy)<1e-7||l<1e-6)return;for(const t of [.1,.3,.5,.7,.9]){const x=a[0]+dx*t,z=a[1]+dy*t,eps=1e-6;const left=covered([x-dy/l*eps,z+dx/l*eps]),right=covered([x+dy/l*eps,z-dx/l*eps]);if(left!==right){bad.push([a,b]);break;}}}));return {polys:polys.length,diagonal:bad.length,first:bad[0]};};});
const sweep=await p.evaluate(()=>{const rows=[];for(const ei of [2,3])for(const kind of ['wall','cham','top'])for(const offset of [.05,.12])for(const angle of [0,90]){const f=nnPaintFacesTest().find(f=>f.id.ei===ei&&f.id.k===kind);const end=ei===2?Math.max(...f.pts.map(q=>q[0]))-offset:Math.min(...f.pts.map(q=>q[0]))+offset;for(const h of kind==='wall'?[.08,.15,.22,.26]:kind==='cham'?[.005,.02,.037]:[.03,.09]){const hit={point:new THREE.Vector3(...f.p).addScaledVector(new THREE.Vector3(...f.u),end).addScaledVector(new THREE.Vector3(...f.v),h),n:new THREE.Vector3(...f.n)};const F=nnSheetSizeFaces(hit,400,400,angle);rows.push({ei,kind,offset,angle,h,...topAudit(F),area:F.reduce((a,f)=>a+f.am,0)});}}return rows;});
ok(sweep.length===72&&sweep.every(r=>r.diagonal===0),'左右・上下72位置で天端の外周に斜めの切れ目を作らない',sweep.filter(r=>r.diagonal));ok(sweep.every(r=>Number.isFinite(r.area)&&r.area>0&&r.area<=.160001),'全位置で実在面に貼付・400×400の面積を超えない',sweep.filter(r=>!Number.isFinite(r.area)||r.area<=0||r.area>.160001));
await p.evaluate(()=>{d3ViewIso();nnRoofFold(true);T.theta=Math.PI*1.25;T.phi=1;T.tx=1.74;T.tz=1.74;T.r=2;T.rev++;nnSheetStart({n:'検査増貼り',col:'#cc0000'},'size');nnSheetMode.w=400;nnSheetMode.d=400;nnCond.close();});await p.waitForFunction(()=>{const k=T.camera.position.toArray().join();window.__stable=window.__last===k?(window.__stable||0)+1:0;window.__last=k;return __stable>4;});
const point=await p.evaluate(()=>{let v=new THREE.Vector3(1.794,.292,1.756).project(T.camera),r=T.renderer.domElement.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};});await p.mouse.click(point.x,point.y);await p.screenshot({path:'.codex-finalizer/sizetop-'+(process.argv[2]?'before-':'')+'preview.png'});await p.locator('[data-size-commit]').click();const saved=await p.evaluate(()=>state.d3sheet[0]&&topAudit(state.d3sheet[0].faces));ok(saved&&saved.polys>=2&&saved.diagonal===0,'添付と同じ下地表示でクリック・確定後も天端の外周が直角',saved);await p.screenshot({path:'.codex-finalizer/sizetop-'+(process.argv[2]?'before-':'')+'finished.png'});await p.evaluate(()=>saveState());await p.reload();await p.waitForFunction(()=>typeof state!=='undefined');ok(await p.evaluate(()=>state.d3sheet[0]?.part?.w===400),'保存・再読込で400mmを保持');ok(errors.length===0,'実行エラーなし',errors);
}finally{await b.close();}process.exitCode=bad?1:0;})().catch(e=>{console.error(e);process.exitCode=1;});
