const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let bad=0;const ok=(c,m,v)=>{console.log((c?'○ ':'★NG ')+m+(v===undefined?'':' '+JSON.stringify(v)));if(!c)bad++;};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{const u=new URL(r.request().url());let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/zumen_sekisan.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='sizecorner.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});await p.goto('https://sizecorner.test/zumen_sekisan.html');await p.evaluate(()=>{nnZMenuClose();state.scaleM=1;state.polys=[{pts:[{x:0,y:0},{x:4,y:0},{x:4,y:2},{x:2,y:2},{x:2,y:4},{x:0,y:4}],edges:Array.from({length:6},()=>({k:'para',h:600,w:250})),holes:[],lv:0}];state.parts=[];state.d3sheet=[];state.active=0;setTab('d3');});await p.waitForFunction(()=>T&&T.group&&T.group.children.length>3);
await p.evaluate(()=>{window.testCovers=function(f,x,z){if(f.id.k!=='deck')return false;const W=f.pts.map(q=>new THREE.Vector3(...f.p).addScaledVector(new THREE.Vector3(...f.u),q[0]).addScaledVector(new THREE.Vector3(...f.v),q[1]));let inside=false;for(let i=0,j=W.length-1;i<W.length;j=i++){const a=W[i],b=W[j];if((a.z>z)!==(b.z>z)&&x<(b.x-a.x)*(z-a.z)/(b.z-a.z)+a.x)inside=!inside;}return inside;};});
for(const height of [600,300]){await p.evaluate(h=>{state.polys[0].edges.forEach(e=>e.h=h);dirty3d=true;build3D();},height);
const cases=await p.evaluate(()=>{const C=1.744,V=q=>new THREE.Vector3(...q);return [0,1].flatMap(side=>[0,90].map(angle=>{const point=side?[C,.15,C+.02]:[C+.02,.15,C],n=side?[-1,0,0]:[0,0,-1];const f=nnSheetSizeFaces({point:V(point),n:V(n)},400,400,angle);return {side,angle,left:f.some(g=>testCovers(g,C+.10,C-.03)),right:f.some(g=>testCovers(g,C-.03,C+.10)),outsideLeft:f.some(g=>testCovers(g,C+.10,C-.10)),outsideRight:f.some(g=>testCovers(g,C-.10,C+.10)),area:f.reduce((s,f)=>s+Math.abs(f.pts.reduce((a,q,i)=>{const r=f.pts[(i+1)%f.pts.length];return a+q[0]*r[1]-r[0]*q[1];},0))/2,0)};}));});
cases.forEach(r=>ok(r.left&&r.right&&!r.outsideLeft&&!r.outsideRight,'高さ'+height+'mm・左右どちらから置いても平場の両側に折返し',r));if(height===600)cases.forEach(r=>ok(Math.abs(r.area-.16)<1e-7,'400×400の面積0.16㎡を維持',r.area));}
await p.evaluate(()=>{d3ViewIso();nnRoofFold(true);T.theta=Math.PI*1.25;T.phi=1.15;T.tx=1.74;T.tz=1.74;T.r=2.5;T.rev++;nnSheetStart({n:'検査増貼り',col:'#cc0000'},'size');nnSheetMode.w=400;nnSheetMode.d=400;nnCond.close();});await p.waitForFunction(()=>{const k=T.camera.position.toArray().join();window.__stable=window.__last===k?(window.__stable||0)+1:0;window.__last=k;return __stable>4;});
const point=await p.evaluate(()=>{let v=new THREE.Vector3(1.78,.15,1.744).project(T.camera),r=T.renderer.domElement.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};});await p.mouse.click(point.x,point.y);await p.screenshot({path:'.codex-finalizer/sizecorner-'+(process.argv[2]?'before-':'')+'preview.png'});
const preview=await p.evaluate(()=>{const g=T.scene.getObjectByName('nnSheetCornerPreview');return g&&g.children.length;});ok(preview>0,'水色の予告を表示',preview);await p.locator('[data-size-commit]').click();
const saved=await p.evaluate(()=>{const s=state.d3sheet[0],C=1.744;return s&&{left:s.faces.some(f=>testCovers(f,C+.10,C-.03)),right:s.faces.some(f=>testCovers(f,C-.03,C+.10)),outside:s.faces.some(f=>testCovers(f,C+.10,C-.10)||testCovers(f,C-.10,C+.10)),faces:s.faces.length};});ok(saved&&saved.left&&saved.right&&!saved.outside,'ここに貼るで確定後も両側が規定幅の折返し',saved);await p.screenshot({path:'.codex-finalizer/sizecorner-'+(process.argv[2]?'before-':'')+'finished.png'});await p.evaluate(()=>saveState());await p.reload();await p.waitForFunction(()=>typeof state!=='undefined');ok(await p.evaluate(()=>state.d3sheet[0]?.part?.w===400&&state.d3sheet[0]?.faces.filter(f=>f.id.k==='deck').length>=2),'保存・再読込で両側の平場を保持');ok(errors.length===0,'実行エラーなし',errors);
}finally{await b.close();}process.exitCode=bad?1:0;})().catch(e=>{console.error(e);process.exitCode=1;});
