/* ★2026-09-04i 工程バー（下地／既存防水／施工後）と光（標準・朝・昼・夕）＝§282
   使い方: node _check/stage1.js ／ node _check/stage1.js ph */
const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{
const ph=process.argv[2]==='ph'; const R=[]; const ok=(n,c,d)=>R.push((c?'○ ':'★NG ')+n+(d?'  '+d:''));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const ctx=await b.newContext(ph?{viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true}:{viewport:{width:2000,height:1010}});
const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('dialog',d=>d.accept());
if(ph) await p.addInitScript(()=>{Object.defineProperty(screen,'width',{get:()=>393});Object.defineProperty(screen,'height',{get:()=>852});});
await p.goto('http://localhost:8899/zumen_sekisan.html'); await p.waitForTimeout(900);
const h0=await p.evaluate(()=>document.querySelector('header').getBoundingClientRect().height);
await p.evaluate(()=>{try{nnZMenuClose();}catch(_){}}); await p.waitForTimeout(400);
const r=await p.evaluate(()=>{const d=document.getElementById('nnStageBar');return {parent:d&&d.parentNode.tagName, cls:d&&d.className, disp:d&&getComputedStyle(d).display, btns:d?[...d.querySelectorAll('button')].map(b=>b.dataset.st):[], hh:document.querySelector('header').getBoundingClientRect().height};});
ok('①工程バーが出ている（3択）', r.disp==='flex'&&r.btns.join(',')==='body,exist,', JSON.stringify(r.btns));
if(!ph) ok('①PCは帯の中・帯は厚くならない', r.parent==='HEADER'&&Math.abs(r.hh-h0)<2, r.parent+' '+h0+'→'+r.hh);
else   ok('①スマホは方眼の上に浮く', r.parent==='MAIN'&&r.cls.indexOf('flt')>=0, r.parent+' '+r.cls);
await p.evaluate(()=>{ loadSample(); }); await p.waitForTimeout(400);
const cols=await p.evaluate(()=>[...document.querySelectorAll('#nnRoofTbl th')].map(t=>t.textContent).join(','));
if(!ph) ok('②屋根の表に「現況」の列は無い', cols.length>0&&!/現況/.test(cols), cols);
await p.click('#nnStageBar button[data-st="exist"]'); await p.waitForTimeout(250);
ok('③押すと state.genkyo が変わり、点灯も移る', (await p.evaluate(()=>state.genkyo+'|'+document.querySelector('#nnStageBar button.on').dataset.st))==='exist|exist');
const fills=await p.evaluate(()=>{const o={}; ['body','exist',''].forEach(k=>{nnStageSet(k); o[k||'new']=nnStageFill2D(state.polys[0]);}); return o;});
ok('④平面図の塗りが工程で変わる（下地＝灰／既存＝くすんだ色／施工後＝仕様の色）', fills.body==='#c4c8c2'&&/^#/.test(fills.exist)&&fills.new===null, JSON.stringify(fills));
const per=await p.evaluate(()=>{ state.polys[0].genkyo='body'; nnStageSet('exist'); return state.polys.map(x=>x.genkyo||'-').join(''); });
ok('④屋根ごとの古い現況は切り替えのたびに消える（図面ぜんぶで1つ）', per==='---', per);
await p.evaluate(()=>setTab('d3')); await p.waitForTimeout(3500);
const d3=await p.evaluate(()=>({sky:nnSkyKind(), kinds:Object.keys(NN_SKY).join(','), bar:document.getElementById('nnSkyBar').innerText.replace(/\s+/g,' '), T:typeof T!=='undefined'&&!!T.scene}));
ok('⑤光は 標準・朝・昼・夕（夜は無い）・既定は標準', d3.kinds==='std,asa,hiru,yuu'&&d3.sky==='std', JSON.stringify(d3));
const fp=async(k)=>{ await p.evaluate(kk=>nnStageSet(kk),k); await p.waitForTimeout(1200);
  return await p.evaluate(()=>{ const r=T.renderer, gl=r.getContext(); r.render(T.scene,T.camera);
    const w=64,h=64,buf=new Uint8Array(w*h*4), fw=gl.drawingBufferWidth, fh=gl.drawingBufferHeight;
    gl.readPixels((fw>>1)-32,(fh>>1)-32,w,h,gl.RGBA,gl.UNSIGNED_BYTE,buf); let s=0; for(let i=0;i<buf.length;i+=4) s+=buf[i]+buf[i+1]*3+buf[i+2]*7;
    let aged=0,white=0; T.group.traverse(o=>{ if(o.isMesh&&o.material&&o.material.map&&o.material.color){ if(o.material.userData&&o.material.userData.nnAged) aged++; else if(o.material.color.r>0.99) white++; } });
    return {s,aged,white}; }); };
const A=await fp(''), B=await fp('body'), C=await fp('exist');
ok('⑥3Dが工程で変わる（3通りとも絵が違う）', new Set([A.s,B.s,C.s]).size===3, [A.s,B.s,C.s].join('/'));
ok('⑥既存防水は「くすませた」材質（劣化）・施工後は白（きれい）', C.aged>0&&A.aged===0, 'exist.aged='+C.aged+' new.aged='+A.aged);
const cam0=await p.evaluate(()=>[T.theta,T.phi,T.r,T.tx,T.tz].join(','));
await p.evaluate(()=>nnStageSet('body')); await p.waitForTimeout(300);
ok('⑦工程を変えてもカメラは動かない（§152）', (await p.evaluate(()=>[T.theta,T.phi,T.r,T.tx,T.tz].join(',')))===cam0);
await p.evaluate(()=>{ state.kubun='shinchiku'; saveState(); nnStageBar(); }); await p.waitForTimeout(400);
ok('⑧新築では「既存防水」を出さない', (await p.evaluate(()=>[...document.querySelectorAll('#nnStageBar button')].map(b=>b.dataset.st).join(',')))==='body,');
await p.evaluate(()=>{ nnStageSet('exist'); }); 
ok('⑧新築で既存を選んでも施工後に丸める', (await p.evaluate(()=>state.genkyo||'(なし)'))==='(なし)');
await p.evaluate(()=>{ state.kubun='kaishu'; nnStageSet('exist'); saveState(); }); await p.waitForTimeout(300);
await p.reload(); await p.waitForTimeout(1500); await p.evaluate(()=>{try{nnZMenuClose();}catch(_){}});
ok('⑨保存して開き直しても残る', (await p.evaluate(()=>state.genkyo))==='exist');
await p.evaluate(()=>setTab('sec')); await p.waitForTimeout(300);
ok('⑩断面図タブでは出さない', (await p.evaluate(()=>getComputedStyle(document.getElementById('nnStageBar')).display))==='none');
ok('JSエラーなし', errs.length===0, errs.slice(0,2).join(' / '));
console.log(R.join('\n')); console.log('★NG '+R.filter(x=>x[0]==='★').length+' / '+R.length+'件');
await b.close();})();
