/* 3Dの可視頂点・辺・面・範囲を実ドラッグし、完成座標と保存を確認。 */
const fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/jiruh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let bad=0;const ok=(c,n,v)=>{console.log((c?'○ ':'★NG ')+n+' '+JSON.stringify(v));if(!c)bad++;};
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:1500,height:1000}}),errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname==='/ver.txt')return r.abort();let f=path.resolve(decodeURIComponent(u.pathname).slice(1));if(u.pathname==='/zumen_sekisan.html'&&process.argv[2])f=path.resolve(process.argv[2]);return u.hostname==='select.test'&&f.startsWith(process.cwd()+path.sep)&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});
await p.goto('https://select.test/zumen_sekisan.html');await p.evaluate(()=>{nnZMenuClose();setTab('d3');});await p.waitForFunction(()=>window.nnD3PointDbg&&T?.renderer&&document.getElementById('nnQuickBar'));
async function reset(){await p.evaluate(()=>{setTool('none');state.scaleM=1;state.polys=[{name:'検査屋根',pts:[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4}],edges:Array.from({length:4},()=>({k:'para',h:600,w:250})),holes:[],lv:0}];state.d3sheet=[];state.parts=[];state.d3sol=[];state.active=0;dirty3d=true;build3D();d3ViewIso();T.theta=Math.PI*.25;T.phi=1.05;T.tx=1;T.tz=1;T.r=6;T.rev=(T.rev|0)+1;saveState();});await p.waitForFunction(()=>{const k=T.camera.position.toArray().join();window.__same=window.__last===k?(window.__same||0)+1:0;window.__last=k;return __same>3;});}
const sc=async(a)=>p.evaluate(a=>{var v=new THREE.Vector3(...a).project(T.camera),r=T.renderer.domElement.getBoundingClientRect();return {x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};},a);
async function drag(a,z){await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:8});await p.mouse.up();await p.waitForFunction(()=>!window.nnD3PointDbg().drag);}


await reset();await p.evaluate(()=>{state.polys=[{name:'低い屋根',pts:[{x:0,y:0},{x:10,y:0},{x:10,y:4},{x:5,y:4},{x:2,y:2},{x:2,y:4},{x:0,y:4}],edges:Array.from({length:7},()=>({k:'para',h:300,w:250})),holes:[],lv:.5},{name:'高い屋根',pts:[{x:2,y:2},{x:5,y:4},{x:5,y:6},{x:2,y:6}],edges:Array.from({length:4},()=>({k:'para',h:300,w:250})),holes:[],lv:1.5}];state.active=1;dirty3d=true;build3D();T.theta=1.4;T.phi=1.2;T.tx=3.5;T.tz=4;T.r=8;T.rev++;});
await p.waitForFunction(()=>{const k=T.camera.position.toArray().join();window.__same=window.__last===k?(window.__same||0)+1:0;window.__last=k;return __same>3;});
await p.locator('#tl_sel_face').click();const a=await sc([3.5,1,6]);await p.mouse.click(a.x,a.y);ok((await p.evaluate(()=>sel))?.f==='out','段差の外側を実クリック',await p.evaluate(()=>sel));
const h=await p.evaluate(()=>{let rows=[];T.scene.updateMatrixWorld(true);T.scene.traverse(o=>{if(o.isMesh&&o.userData.face){const at=o.geometry.attributes.position;rows.push({f:o.userData.face,depth:o.material.depthTest,points:at.count,box:new THREE.Box3().setFromObject(o).min.toArray()});}});return rows;});ok(h.length>0&&h.every(x=>x.depth),'選択面は手前の躯体を透過しない',h);await p.screenshot({path:'_check/visible-face.png'});
const probes=await p.evaluate(()=>{const mesh=[];T.scene.traverse(o=>{if(o.isMesh&&o.userData.face==='out')mesh.push(o);});let total=0,bad=0;for(let x=2.05;x<5;x+=.1)for(let y=.05;y<1.81;y+=.1){const ray=new THREE.Raycaster(new THREE.Vector3(x,y,8),new THREE.Vector3(0,0,-1)),real=ray.intersectObjects(T.group.children,true).find(h=>nnPaintMeshVisible(h.object)),red=ray.intersectObjects(mesh,true)[0];if(red){total++;if(!real||Math.abs(red.distance-real.distance)>.002)bad++;}}return {total,bad};});ok(probes.total>100&&probes.bad===0,'完成した選択面の各点が実際の表面に一致',probes);
const coverage=await p.evaluate(()=>{let checked=0,missing=0,miss=[],mismatch=0,kinds=new Set(),cache=new Map();for(let ix=-9;ix<=9;ix++)for(let iy=-6;iy<=6;iy++){const rc=new THREE.Raycaster();rc.setFromCamera(new THREE.Vector2(ix/10,iy/10),T.camera);const hit=rc.intersectObjects(T.group.children,true).find(h=>nnPaintMeshVisible(h.object));if(!hit||hit.object.userData.nnRoofOwner==null)continue;checked++;const pk=window.nnRoofFacePick?nnRoofFacePick(rc):null;if(!pk){missing++;miss.push({name:hit.object.name,data:hit.object.userData,n:hit.face.normal.toArray(),w:hit.point.toArray()});continue;}kinds.add(pk.f);const key=JSON.stringify(pk);if(!cache.has(key)){const g=nnRoofFaceGeometry(pk);cache.set(key,g?new THREE.Mesh(g,new THREE.MeshBasicMaterial({side:THREE.DoubleSide})):null);}const mesh=cache.get(key),red=mesh&&rc.intersectObject(mesh)[0];if(!red||Math.abs(red.distance-hit.distance)>.01)mismatch++;}cache.forEach(m=>{if(m){m.geometry.dispose();m.material.dispose();}});return {checked,missing,miss,mismatch,kinds:[...kinds]};});ok(coverage.checked>30&&coverage.missing===0&&coverage.mismatch===0,'画面内の見える面を走査して選択欠落・奥の面への誤選択なし',coverage);
await drag(a,{x:a.x,y:a.y+45});const moved=await p.evaluate(()=>state.polys[1].pts);ok(moved[2].y!==6&&moved[3].y!==6,'選んだ面をドラッグして押し引き',moved);await p.evaluate(()=>{setTool('none');state.polys=[{name:'段欠きの実面',pts:[{x:0,y:0},{x:6,y:0},{x:6,y:3},{x:3,y:3},{x:3,y:6},{x:0,y:6}],edges:Array.from({length:6},(_,i)=>({k:'para',h:i===2?1200:600,w:250})),holes:[],lv:.5}];state.active=0;dirty3d=true;build3D();pick3({p:0,r:-1,e:2,f:'out'});});
const notch=await p.evaluate(()=>{T.scene.updateMatrixWorld(true);const red=[];T.scene.traverse(o=>{if(o.isMesh&&o.userData.face==='out')red.push(o);});return [[2.85,.5],[2.85,1.4],[3.5,.3]].map(q=>{const ray=new THREE.Raycaster(new THREE.Vector3(q[0],q[1],3.1),new THREE.Vector3(0,0,-1));const real=ray.intersectObjects(T.group.children,true).find(h=>nnPaintMeshVisible(h.object));const selected=ray.intersectObjects(red,true)[0];return {q,real:real?.distance,red:selected?.distance};});});ok(!notch[0].red&&notch[1].red!=null&&notch[2].red!=null&&notch.slice(1).every(x=>Math.abs(x.red-x.real)<.002),'長方形に戻さず上部だけ張り出す段欠きの実輪郭を選択',notch);
await p.evaluate(()=>{nnRoofFold(true);T.theta=1.5;T.phi=1.2;T.tx=3.5;T.tz=3;T.r=7;T.rev++;});await p.waitForFunction(()=>{const k=T.camera.position.toArray().join();window.__same=window.__last===k?(window.__same||0)+1:0;window.__last=k;return __same>3;});await p.screenshot({path:'_check/visible-face-notch.png'});ok(errs.length===0,'実行エラーなし',errs);await b.close();process.exitCode=bad?1:0;})().catch(e=>{console.error(e);process.exitCode=1;});



