const {chromium}=require('/opt/node22/lib/node_modules/playwright');
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
(async()=>{
  const b=await chromium.launch({executablePath:EXE});
  const p=await (await b.newContext({viewport:{width:1600,height:900}})).newPage();
  const cdp=await p.context().newCDPSession(p);
  await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
  const t0=Date.now();
  await p.goto('http://localhost:8899/kirokucho_demo.html',{waitUntil:'load'});
  console.log('load まで', Date.now()-t0, 'ms');
  await p.waitForTimeout(2500);
  const t=async(l,fn)=>console.log(l.padEnd(30), await p.evaluate(fn)+'ms');
  await p.evaluate(()=>showView('list')); await p.waitForTimeout(1200);
  await t('絞り込みメニューを開く', ()=>{const el=document.querySelector('#chips .dfil button');
    const a=performance.now(); el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,isPrimary:true,pointerId:1}));
    return Math.round(performance.now()-a);});
  await p.waitForTimeout(500);
  await p.evaluate(()=>{ if(window.nnClosePortal)nnClosePortal(); });
  await t('物件の詳細を開く', ()=>{selectedId=props[1].id; const a=performance.now(); openDetailFull(); return Math.round(performance.now()-a);});
  await p.waitForTimeout(800);
  await t('詳細のタブ切替(写真)', ()=>{const a=performance.now(); curTab='写真'; renderDetail(); return Math.round(performance.now()-a);});
  await p.waitForTimeout(600);
  await t('一覧へ戻る', ()=>{const a=performance.now(); showView('list'); return Math.round(performance.now()-a);});
  await p.waitForTimeout(900);
  await t('新規作成フォームを開く', ()=>{const a=performance.now(); openModal(); return Math.round(performance.now()-a);});
  await p.waitForTimeout(600);
  await t('工程表タブへ', ()=>{const a=performance.now(); if(window.closeModal)closeModal(); showView('sched'); return Math.round(performance.now()-a);});
  await p.waitForTimeout(1500);
  await b.close();
})();
